apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockchain-service
  name: blockchain-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: blockchain-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blockchain-service
  name: blockchain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
        - image: medicalife/blockchain-service
          name: blockchain-service
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: blockchain-config
      dnsConfig:
        nameservers:
          - 8.8.8.8
      restartPolicy: Always