apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-config
data:
  BLOCKCHAIN_MSPID: 'Hopital1MSP'
  BLOCKCHAIN_PeerHostAlias: 'peer0.hopital1.medicalife.com'
  BLOCKCHAIN_PeerHostEndpoint: 'blockchain-node:7051'
  BLOCKCHAIN_PeerTLSCACert: |
    -----BEGIN CERTIFICATE-----
    MIICdjCCAhygAwIBAgIRAOohDdBMsxSLAYB+rA/0TeYwCgYIKoZIzj0EAwIwgYQx
    CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
    RnJhbmNpc2NvMSAwHgYDVQQKExdob3BpdGFsMS5tZWRpY2FsaWZlLmNvbTEmMCQG
    A1UEAxMddGxzY2EuaG9waXRhbDEubWVkaWNhbGlmZS5jb20wHhcNMjQwNTA1MTUx
    MTAwWhcNMzQwNTAzMTUxMTAwWjCBhDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNh
    bGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xIDAeBgNVBAoTF2hvcGl0
    YWwxLm1lZGljYWxpZmUuY29tMSYwJAYDVQQDEx10bHNjYS5ob3BpdGFsMS5tZWRp
    Y2FsaWZlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLkYVzm2cP3H9BMF
    EhEWtcj6JTsdezVdVACHNTgXTE/F12QGAsSikbUKRmfrRgJtsrc0RUfxSAk3JzDS
    MVbSWMyjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
    KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgzzPQ9a7EU+Q0caHz
    fOU2L3upFtuZpir32YmSkGXaMdUwCgYIKoZIzj0EAwIDSAAwRQIhAKqRMq7As/bH
    9/b9be35BUFNNSblMqi+12CyyeKcqBvTAiBliXarH+cQncexRn8IGsn1SnLdAVnD
    reFNHhYrccYvzQ==
    -----END CERTIFICATE-----
  BLOCKCHAIN_UserPublicKey: |
    -----BEGIN CERTIFICATE-----
    MIICLjCCAdWgAwIBAgIQdJnDVYJ8//CekzrNdkMguTAKBggqhkjOPQQDAjCBgTEL
    MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
    cmFuY2lzY28xIDAeBgNVBAoTF2hvcGl0YWwxLm1lZGljYWxpZmUuY29tMSMwIQYD
    VQQDExpjYS5ob3BpdGFsMS5tZWRpY2FsaWZlLmNvbTAeFw0yNDA1MDUxNTExMDBa
    Fw0zNDA1MDMxNTExMDBaMGIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9y
    bmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMSYwJAYDVQQDDB1BZG1pbkBob3Bp
    dGFsMS5tZWRpY2FsaWZlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAnN
    jZXGziJMXkwjylnAKCQFM3+SEUruOI606M/Ch0taEDstG0TW+O4853HqEZiAMS6R
    AeKusasThgAbmwJnHqCjTTBLMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAA
    MCsGA1UdIwQkMCKAIKvM86bP6zXysfhqNGUSH3FYs8pE1Sa4E5ceJyh33OdbMAoG
    CCqGSM49BAMCA0cAMEQCIB3tAlP2F2nEhs62b0yiH0d31Tki3UzR0MF3RjUpA8v6
    AiAZ5frpk0caU+ePs6f3nrzijaOQ0svoiAp0s1NI7HUzSg==
    -----END CERTIFICATE-----
  BLOCKCHAIN_UserSecretKey: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQglT/6LHfEJcst8H4Q
    gRi1VJFvOOi1g3knfP7QphmPwzyhRANCAAQJzY2Vxs4iTF5MI8pZwCgkBTN/khFK
    7jiOtOjPwodLWhA7LRtE1vjuPOdx6hGYgDEukQHirrGrE4YAG5sCZx6g
    -----END PRIVATE KEY-----
