apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-config
data:
  BLOCKCHAIN_MSPID: 'NordMSP'
  BLOCKCHAIN_PeerHostAlias: 'peer0.nord.medicalife.dz'
  BLOCKCHAIN_PeerHostEndpoint: 'blockchain-node:8051'
  BLOCKCHAIN_PeerTLSCACert: |
    -----BEGIN CERTIFICATE-----
    MIICYDCCAgagAwIBAgIRAM5k+mI7C2JSEnm4QPXCxKswCgYIKoZIzj0EAwIwejEL
    MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
    cmFuY2lzY28xGzAZBgNVBAoTEm5vcmQubWVkaWNhbGlmZS5kejEhMB8GA1UEAxMY
    dGxzY2Eubm9yZC5tZWRpY2FsaWZlLmR6MB4XDTI0MDUxMjIwMzUwMFoXDTM0MDUx
    MDIwMzUwMFowejELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAU
    BgNVBAcTDVNhbiBGcmFuY2lzY28xGzAZBgNVBAoTEm5vcmQubWVkaWNhbGlmZS5k
    ejEhMB8GA1UEAxMYdGxzY2Eubm9yZC5tZWRpY2FsaWZlLmR6MFkwEwYHKoZIzj0C
    AQYIKoZIzj0DAQcDQgAEMMqJsuzYCIN3s6y+UoJjBblqVX7Pbi10JdDFM2XDNnzv
    CEINxTNNZ9iph4ZSizyS0kXaP7a5WIpIv1MaFT87yaNtMGswDgYDVR0PAQH/BAQD
    AgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTAD
    AQH/MCkGA1UdDgQiBCBRs3K6cJ3TDydOiq2LCKtnrhDuYkTmh7DnX9VM35D24DAK
    BggqhkjOPQQDAgNIADBFAiEA4H0+PW6kCxxh7vFvWL0r03WBAbCoTteMylYC4+IS
    mYsCIE7hghGJc++v7YQnTTO07hSiKr4wik2afz/MTOcRlwBX
    -----END CERTIFICATE-----
  BLOCKCHAIN_UserPublicKey: |
    -----BEGIN CERTIFICATE-----
    MIICHzCCAcWgAwIBAgIQYX55x1ZlWvGTul0D26WCjTAKBggqhkjOPQQDAjB3MQsw
    CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
    YW5jaXNjbzEbMBkGA1UEChMSbm9yZC5tZWRpY2FsaWZlLmR6MR4wHAYDVQQDExVj
    YS5ub3JkLm1lZGljYWxpZmUuZHowHhcNMjQwNTEyMjAzNTAwWhcNMzQwNTEwMjAz
    NTAwWjBdMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
    BxMNU2FuIEZyYW5jaXNjbzEhMB8GA1UEAwwYQWRtaW5Abm9yZC5tZWRpY2FsaWZl
    LmR6MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuFXoaiG13oO/aX6ljSZXbvCr
    yU+QC4GotOX0bLNcPzGQwAxSxcSA6lUex2l42KDOsYPaO03k3t1hSkLZhGDWh6NN
    MEswDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwKwYDVR0jBCQwIoAg4Upg
    SFFxpfZYAyHXs08HXsrBRRl4BtZAa0uCco0fCuMwCgYIKoZIzj0EAwIDSAAwRQIh
    AM7HU6Y8Nwd30kFyX/PWjtQvlTnf5IarkgGGsWoOZCKIAiBKl0YIzqCROSByZvky
    Q0qEZN4FXETP+Ewq4KlZU4TnbA==
    -----END CERTIFICATE-----
  BLOCKCHAIN_UserSecretKey: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfTap+WFPqZK/x1+c
    MkvyKbnnWeX+5KqM90kdmhDoZLqhRANCAAS4VehqIbXeg79pfqWNJldu8KvJT5AL
    gai05fRss1w/MZDADFLFxIDqVR7HaXjYoM6xg9o7TeTe3WFKQtmEYNaH
    -----END PRIVATE KEY-----
