apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockchain-node
  name: blockchain-node
spec:
   clusterIP: None
   type: ClusterIP
   ports:
   - protocol: TCP
     port: 7051
     targetPort: 7051
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: blockchain-node
  name: blockchain-node
subsets:
  - addresses:
    - ip: 192.168.43.200
    ports:
      - port: 7051