apiVersion: v1
kind: Service
metadata:
  labels:
    app: pharmacy-db
  name: pharmacy-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: pharmacy-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pharmacy-db
  name: pharmacy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmacy-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pharmacy-db
    spec:
      containers:
        - image: abdou1307/pharmacy-db:latest
          name: pharmacy-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/pharmacy
              name: pharmacy-data
      restartPolicy: Always
      volumes:
        - name: pharmacy-data
          persistentVolumeClaim:
            claimName: pharmacy-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pharmacy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi