apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications-db
  name: notifications-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: notifications-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications-db
  name: notifications-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notifications-db
    spec:
      containers:
        - image: medicalife/notifications-db
          name: notifications-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/notifications
              name: notifications-data
      restartPolicy: Always
      volumes:
        - name: notifications-data
          persistentVolumeClaim:
            claimName: notifications-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi