apiVersion: v1
kind: Service
metadata:
  labels:
    app: chambres-lits-db
  name: chambres-lits-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: chambres-lits-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chambres-lits-db
  name: chambres-lits-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chambres-lits-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chambres-lits-db
    spec:
      containers:
        - image: hospital1307/chambres-lits-db:latest
          name: chambres-lits-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/chambres-lits
              name: chambres-lits-data
      restartPolicy: Always
      volumes:
        - name: chambres-lits-data
          persistentVolumeClaim:
            claimName: chambres-lits-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chambres-lits-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi