apiVersion: v1
kind: Service
metadata:
  labels:
    app: codification-service
  name: codification-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: codification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codification-service
  name: codification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codification-service
  template:
    metadata:
      labels:
        app: codification-service
    spec:
      containers:
        - image: abdou1307/codification-service:latest
          name: codification-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
