apiVersion: v1
kind: Service
metadata:
  labels:
    app: consultations-db
  name: consultations-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: consultations-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consultations-db
  name: consultations-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultations-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: consultations-db
    spec:
      containers:
        - image: medicalife/consultations-db
          name: consultations-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/consultations
              name: consultations-data
      restartPolicy: Always
      volumes:
        - name: consultations-data
          persistentVolumeClaim:
            claimName: consultations-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consultations-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi