apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-db
  name: auth-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: auth-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-db
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - image: abdou1307/auth-db:latest
          name: auth-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/auth
              name: auth-data
      restartPolicy: Always
      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi