apiVersion: v1
kind: Service
metadata:
  labels:
    app: hospitalisations-service
  name: hospitalisations-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hospitalisations-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hospitalisations-service
  name: hospitalisations-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospitalisations-service
  template:
    metadata:
      labels:
        app: hospitalisations-service
    spec:
      containers:
        - image: medicalife/hospitalisations-service:latest
          name: hospitalisations-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: blockchain-config
      dnsConfig:
        nameservers:
          - 8.8.8.8
      restartPolicy: Always