apiVersion: v1
kind: Service
metadata:
  labels:
    app: prescriptions-bilans-radios-service
  name: prescriptions-bilans-radios-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: prescriptions-bilans-radios-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prescriptions-bilans-radios-service
  name: prescriptions-bilans-radios-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescriptions-bilans-radios-service
  template:
    metadata:
      labels:
        app: prescriptions-bilans-radios-service
    spec:
      containers:
        - image: medicalife/prescriptions-bilans-radios-service:latest
          name: prescriptions-bilans-radios-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pv-prescriptions
              mountPath: /mnt/data
      dnsConfig:
        nameservers:
          - 8.8.8.8
      restartPolicy: Always
      volumes:
      - name: pv-prescriptions
        persistentVolumeClaim:
          claimName: pvc-prescriptions
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prescriptions
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prescriptions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi