apiVersion: v1
kind: Service
metadata:
  labels:
    app: reception-db
  name: reception-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: reception-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reception-db
  name: reception-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reception-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reception-db
    spec:
      containers:
        - image: hospital1307/reception-db
          name: reception-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/reception
              name: reception-data
      restartPolicy: Always
      volumes:
        - name: reception-data
          persistentVolumeClaim:
            claimName: reception-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reception-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi