START TRANSACTION;

CREATE DATABASE IF NOT EXISTS forza;
SET CHARACTER SET 'utf8';

USE forza;

CREATE TABLE allergenes (
  `code_allergene` varchar(255) NOT NULL PRIMARY KEY,
  `designation` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `famille` varchar(255) NOT NULL,
  `sous_famille` varchar(255) NOT NULL,
  `code_NABM` varchar(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO allergenes (`code_allergene`,`designation`,`type`,famille,sous_famille,code_NABM) VALUES
  ('AM4','Ammonium quaternaire - myorelaxant','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C1','Pénicilline G','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C1G','Pénicilline G','IgG spécifiques','Médicaments','Médicaments','null'),
  ('C1S','IgG4  spécifiques Pénicilline G','IgG spécifiques sous classes 4','Médicaments','Médicaments','null'),
  ('C2','Penicilline V','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C201','Céphalosporines-mélange (Céfaclor, Céfaxine, Céfotaxime, Céfuroxime)','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C202','Suxamethonium','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C206','ACTH','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C207','Protamine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C208','Tétanus toxoïd','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C209','Chymopapaine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C212','Erythromycine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C213','Gentamicine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C216','Doxycycline','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C217','Acide acétylsalicylique','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C222','Mélange de macrolides','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C223','Sulfaméthoxazol','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C232','Lidocaïne - Xylocaïne®','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C242','Triméthoprime','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C253','Tétracaïne','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C260','Ammonium quaternaire de la morphine','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C261','Pholcodine','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C281','Diclofénac®','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C284','Procaïne','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C286','Ibuprofène','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C2G','Pénicilline V','IgG spécifiques','Médicaments','Médicaments','null'),
  ('C2S','IgG spécifiques Pénicilline V','IgG spécifiques sous classes 4','Médicaments','Médicaments','null'),
  ('C300','Codeïne','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C304','Piroxicam','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C305','Acide clavulanique (Augmentin)','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C308','Céfuroxime - Zinnat','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C309','Céfalexine (Céforexine®)','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C338','Carbamazépine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C388','Kétoprofène','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C398','Métronidazole','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C5','Ampicilline','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C6','Amoxicilline','IgE spécifiques','Médicaments','Médicaments','0968'),
  ('C6G','Amoxicilline','IgG spécifiques','Médicaments','Médicaments','null'),
  ('C7','Céfaclor','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C70','Insuline porcine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C703','Acide benzoïque','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C704','Quinoleine (E104)','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C705','Cyclamate de sodium','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C71','Insuline bovine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C711','Nitrite de sodium','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C713','Parabène','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C717','Tartrazine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C73','Insuline humaine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C74','Gélatine bovine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('C8',' Chlorhexidine','IgE spécifiques','Médicaments','Médicaments','null'),
  ('D1','DermatophagoÏdes pteronyssinus','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D1G','DermatophagoÏdes pteronyssinus','IgG spécifiques','Aéroallergènes','Acariens','null'),
  ('D1S','DermatophagoÏdes pteronyssinus','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D2','DermatophagoÏdes farinae','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D201','Blomia tropicalis','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D201S','Blomia tropicalis','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D202','nDer p 1 (Gr 1 Acariens, D. pteronyssinus)','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D203','rDer p 2 (Gr 2 Acariens, D. pteronyssinus recombinant)','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D205','rDer p 10 (Tropomyosine acariens,  D. pteronyssinus recombinant)','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D2G','Dermatophagoïdes farinae','IgG spécifiques','Aéroallergènes','Acariens','null'),
  ('D2S','Dermatophagoïdes farinae','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D3','Dermatophagoides microceras','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D3S','Dermatophagoides microceras','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D500','Argas reflexus','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D70','Acarus siro','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D71','Lepidoglyphus destructor','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D71G','Lepidoglyphus destructor','IgG spécifiques','Aéroallergènes','Acariens','null'),
  ('D71S','Lepidoglyphus destructor','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D72','Tyrophagus putreus','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D72G','Thyrophagus putreus','IgG spécifiques','Aéroallergènes','Acariens','null'),
  ('D72S','Tyrophagus putreus','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D73','Glycyphagus domesticus','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D73S','Glycyphagus domesticus','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('D74','Euroglyphus maynei','IgE spécifiques','Aéroallergènes','Acariens','1204'),
  ('D74G','Euroglyphyus maynei','IgG spécifiques','Aéroallergènes','Acariens','null'),
  ('D74S','Euroglyphus maynei','IgG spécifiques sous classes 4','Aéroallergènes','Acariens','null'),
  ('E1','Chat - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E101','rCan f1 Chien - recombinant','IgE spécifiques','Composants allergéniques','Animaux - recombinants','1204'),
  ('E102','rCan f2 Chien','IgE spécifiques','Composants allergéniques','Animaux - recombinants','1204'),
  ('E196','Perruche callopsitte - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E197','Perruche callopsitte - déjections','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E198','Perruche callopsitte - protéines','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E1G','Chat','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E1S','Chat - epithelium','IgG spécifiques sous classes 4','Aéroallergènes','Animaux','null'),
  ('E200','Canari - déjections','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E201','Canari - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E202','Renne - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E203','Vison - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E204','Sérum albumine bovine','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E204G','Sérum albumine bovine','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E205','Cheval - protéines du serum','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E206','Lapin - protéines du serum','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E208','Chinchilla','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E209','Gerbille','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E210','Renard','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E211','Lapin - protéines urinaires','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E212','Cochon - protéines urinaires','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E213','Perroquet - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E214','Pinson - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E215','Pigeon - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E216','Cerf - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E217','Furet - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E218','Poulet - fientes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E219','Poulet - protéines du serum','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E220','rFel d 2- recombinant - albumine sérique','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E221','rCan f3 - albumine sérique','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E222','nSus s PSAS - albumine sérique','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E226','rCan f 5 (Chien , Arginine esterase)','IgE spécifiques','Composants allergéniques','Animaux - recombinants','1204'),
  ('E227','rEqu c 1 (Cheval, Lipocaline)','IgE spécifiques','Composants allergéniques','Animaux - recombinants','1204'),
  ('E228','rFel d 4 (Chat, Lipocaline)','IgE spécifiques','Composants allergéniques','Animaux - recombinants','1204'),
  ('E3','Cheval - squames','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E3G','Cheval - squames','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E3S','Cheval (Poils et squames)','IgG spécifiques sous classes 4','Aéroallergènes','Animaux','null'),
  ('E4','Vache - squames','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E5','Chien  (Squames)','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E5G','Chien','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E5S','Chien','IgG spécifiques sous classes 4','Aéroallergènes','Animaux','null'),
  ('E6','Cobaye - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E70','Oie - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E70G','Plumes d''oie','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E71','Souris - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E72','Souris - protéines urinaires','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E73','Rat - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E74','Rat - protéines urinaires','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E75','Rat - protéines du sérum','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E76','Souris - protéines du serum','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E77','Perruche - déjections','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E78','Perruche - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E80','Chèvre - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E80S','Chèvre - epithelium','IgG spécifiques sous classes 4','Aéroallergènes','Animaux','null'),
  ('E81','Mouton - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E82','Lapin - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E83','Porc - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E84','Hamster - epithelium','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E84G','Hamster (squames)','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E85','Poulet - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E86','Canard - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E87','Rat - epithelium + protéines','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E88','Souris - epithelium + protéines','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E89','Dinde - plumes','IgE spécifiques','Aéroallergènes','Animaux','1204'),
  ('E90G','Perruche - protéines du sérum - déjections','IgG spécifiques','Aéroallergènes','Animaux','null'),
  ('E94','rFel d 1 Felis domesticus - recombinant','IgE spécifiques','Composants allergéniques','Animaux - recombinants','1204'),
  ('E94S','IgG rFel d 1 Chat - recombinant','IgG spécifiques sous classes 4','Composants allergéniques','Animaux - recombinants','null'),
  ('EX1','Phanères - chien, chat, cheval, vache','IgE spécifiques','Aéroallergènes','Animaux','1201'),
  ('EX2','Animaux - chat, chien, cobaye, rat, souris','IgE spécifiques','Aéroallergènes','Animaux','1201'),
  ('EX70','Animaux - cobaye, lapin, hamster, rat, souris','IgE spécifiques','Aéroallergènes','Animaux','1201'),
  ('EX71','Mélange de plumes - oie, poulet, canard, dinde','IgE spécifiques','Aéroallergènes','Animaux','1201'),
  ('EX72','Mélange de plumes - perruche,canari,perroquet,pinson','IgE spécifiques','Aéroallergènes','Animaux','1201'),
  ('EX73','Mélange de plumes - oie,  poulet, canard, perroquet','IgE spécifiques','Aéroallergènes','Animaux','1201'),
  ('F1','Oeuf - blanc','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F10','Sésame - graine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F11','Sarrasin - graine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F118','Courgette','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F119','Radis','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F12','Pois - graine','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F124','Epeautre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F12S','Pois','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F13','Arachide','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F13G','Arachide','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F13S','Arachide','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F14','Soja','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F147','f147  Cardeau trois yeux','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F14G','Soja','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F14S','Soja','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F15','Haricot blanc','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F157','Canard (viande)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F162','Nectarine','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F17','Noisette','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F178','Rhubarbe','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F17S','Noisette','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F18','Noix du Brésil','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F182','Haricot de Lima','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F1G','Blanc d''oeuf','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F1S','Blanc d''oeuf','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F2','Lait de vache','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F20','Amande','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F201','Noix de pécan','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F202','Noix de cajou','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F203','Pistache','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F204','Truite','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F205','Hareng','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F206','Maquereau','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F207','Palourde','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F208','Citron','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F208G','Citron','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F209','Pamplemousse','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F20G','Amande','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F210','Ananas','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F210G','Ananas','IgG spécifiques','Aéroallergènes','Aliments d''origine végétale','null'),
  ('F211','Mûre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F212','Champignon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F213','Lapin - viande','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F214','Epinard','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F215','Laitue','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F216','Chou','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F217','Chou de Bruxelles','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F218','Paprika','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F219','Fenouil - graine','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F220','Cannelle','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F221','Café','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F221G','Café','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F222','Thé','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F222G','Thé','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F224','Pavot - graine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F225','Potiron Citrouille','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F226','Citrouille - graine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F227','Bettrave à sucre - graine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F227G','Bettrave à sucre','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F227S','Bettrave à sucre','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F23','Crabe','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F231','Lait bouilli','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F232','Ovalbumine,(Gal d 2)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F232G','Ovalbumine','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F232S','Ovalbumine','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F233','Ovomucoïde,(nGal d 1)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F234','Vanille','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F235','Lentille','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F235S','Lentilles','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F236','Petit lait de vache','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F237','Abricot','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F24','Crevette','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F242','Cerise','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F244','Concombre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F245','Oeuf entier','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F245G','Oeuf','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F245S','Oeuf','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F246','Gomme de guar - Agar','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F247','Miel','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F24S','Crevette','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F25','Tomate','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F253','Pignon de pin','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F254','Limande - carrelet','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F255','Prune','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F256','Noix','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F258','Calamar','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F259','Raisin','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F25S','Tomate','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F26','Porc','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F260','Brocolis','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F261','Asperge','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F262','Aubergine','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F263','Poivre vert','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F264','Anguille','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F265','Cumin','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F266','Muscade - fleur - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F267','Cardamome','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F268','Clou de girofle','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F269','Basilic','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F26G','Porc','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F26S','Porc','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F27','Boeuf','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F270','Gingembre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F271','Anis','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F272','Estragon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F273','Thym','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F274','Marjolaine','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F275','Livèche','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F276','Fenouil','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F277','Aneth','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F278','Feuille de laurier','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F279','Piment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F27G','Boeuf','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F27S','Boeuf','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F280','Poivre noir','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F280G','Poivre noir','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F281','Curry','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F282','Noix de muscade','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F283','Origan','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F284','Dinde - viande','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F285','Elan - viande','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F286','Lait de jument','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F287','Haricot rouge','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F288','Myrtille','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F289','Datte','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F290','Huître','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F291','Chou fleur','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F292','Goyave','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F293','Papaye','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F294','Fruit de la passion','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F295','Carambole','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F296','Caroube','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F297','Gomme arabique','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F298','Gomme tragacanthe','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F299','Châtaigne - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F3','Poisson - morue','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F300','Lait de chèvre','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F300G','Lait de chèvre','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F301','Kaki','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F302','Mandarine','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F303','Flétan','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F304','Langouste','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F305','Fenu grec','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F306','Citron vert - lime','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F307','Merluche - Merlu, colin','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F308','Sardine - S. pilchardus','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F309','Pois chiche','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F31','Carotte','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F310','Vesce bleu','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F311','Limande','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F312','Espadon','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F313','Anchois','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F314','Escargot - helix aspersa','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F315','Haricot vert','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F316','Colza - graine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F317','Coriandre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F318','Arbre à pain - fruit','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F319','Betterave - potagère','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F31S','Carotte','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F320','Ecrevisse','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F321','Cheval - viande','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F322','Groseille rouge','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F323','Conalbumine,(nGal d 3)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F324','Houblon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F325','Lait de brebis','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F326','Petit lait de brebis','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F328','Figue','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F329','Pastèque','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F33','Orange','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F330','Cynorrhodon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F331','Safran','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F332','Menthe','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F333','Lin - graines - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F335','Lupin - graines - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F336','Jujube','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F337','Sole','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F338','Coquille St Jacques','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F339','Poivre de la jamaique','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F33G','Orange','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F33S','Orange','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F340','Rouge Carmin - cochenille','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F341','Canneberge','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F342','Olive noire','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F343','Framboise','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F344','Sauge','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F345','Noix de macadamia','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F346','Ormeau','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F347','Quinoa','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F347S','Quinoa','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F348','Litchi','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F35','Pomme de terre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F351','Crevette rPen a 1 Tropomyosine - recombinant','IgE spécifiques','Composants allergéniques','Origine animale - recombinants','1205'),
  ('F351N','npen a 1 - tropomyosine','IgE spécifiques','Composants allergéniques','Origine animale - recombinants','1205'),
  ('F352','r Ara h 8 Arachis hypogaea - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F352S','r Ara h 8 Arachis hypogaea - recombinants','IgG spécifiques sous classes 4','Composants allergéniques','Origine végétale - recombinants','null'),
  ('F353','rGly m 4 Glycine max - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F354','Noix du Brésil recombinant (rBer e1)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F355','rCyp c1 Parvalbumine - recombinant','IgE spécifiques','Composants allergéniques','Origine animale - recombinants','1205'),
  ('F356','Cassis','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F358','Artichaut','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F35G','Pomme de terre','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F36','Noix de coco','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F369','Poisson chat (Ictalurus Punctatus)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F37','Moule','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F381','f381  Vivaneau campèche','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F384','f384 Sténode','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F3G','Poisson - morue','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F3S','Poisson - morue','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F4','Blé - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F40','Thon','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F401','Nèfle du Japon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F41','Saumon','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F410','Mérou (poisson)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F412','Empereur','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F413','Lieu noir','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F414','f414 Tilapia (poisson)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F415','f415 Doré Jaune (poisson)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F416','rTri a 19 Oméga-5 gliadine','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F417','rApi g 1.01 céleri - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F419','rPru p 1 Pêche - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F41S','Saumon','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F42','f42   Aiglefin ( poisson )','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F420','rPru p 3 Pêche - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F421','rPru p 4 Pêche - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F422','r Ara h 1 Arachis hypogaea - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F422S','r Ara h 1 Arachis hypogaea - recombinants','IgG spécifiques sous classes 4','Composants allergéniques','Origine végétale - recombinants','null'),
  ('F423','r Ara h 2 Arachis hypogaea - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F423S','r Ara h 2 Arachis hypogaea - recombinants','IgG spécifiques sous classes 4','Composants allergéniques','Origine végétale - recombinants','null'),
  ('F424','r Ara h 3 Arachis hypogaea - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F424S','r Ara h 3 Arachis hypogaea - recombinants','IgG spécifiques sous classes 4','Composants allergéniques','Origine végétale - recombinants','null'),
  ('F425','rCor a 8 noisette - recombinant','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F426','RGad c1cabillaud - recombinant','IgE spécifiques','Composants allergéniques','Origine animale - recombinants','1205'),
  ('F427','rAra h 9 (LTP, arachide)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F428','f428 rCor a 1 (PR-10, noisette)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F430','f430 Kiwi - rAct d 8 ; PR-10','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F431','nGly m 5 b-conglycinine, soja','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F432','nGly m 6 glycinine, soja','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F433','f433  rTri a 14 (LTP, blé)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F434','f434 rMal d 1 (PR-10, pomme)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F435','f435 rMal d 3 (LTP, pomme)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F439','f439 rCor a 14 noisette - Albumine 2S','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F44','Fraise','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F440','f440 nCor a 9 noisette -  Globuline 11S','IgE spécifiques','Composants allergéniques','Origine animale - recombinants','1205'),
  ('F441','f441 rJug r 1 (Albumine 2S, noix)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F442','f442 rJug r 3 (LTP, noix)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F443','f443 rAna o 3 (Albumine 2S, noix cajou)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1205'),
  ('F447','R ara h 6','IgE spécifiques','Composants allergéniques','Aliments d''origine végétale','1205'),
  ('F44S','Fraise','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F45','Levure de bière','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F47','Ail','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F47G','Ail','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F47S','Ail','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F48','Oignon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F49','Pomme','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F49G','Pomme','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F49S','Pomme','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F4G','Blé - aliment','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F4S','Blé','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F5','Seigle','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F50','Maquereau du pacifique','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F51','Pousse de bambou','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F54','Patate douce','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F55','Millet commun','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F56','Millet italien','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F57','Millet japonais','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F58','Calamar du pacifique','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F59','Poulpe','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F5G','Seigle','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F6','Orge - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F60','Maquereau commun','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F600','livetine (jaune oeuf)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F61','Sardinops du japon','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F6G','Orge - aliment','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F6S','Orge','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F7','Avoine - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F700','Alpha-gal (Thyroglobuline)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F75','Oeuf - Jaune','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F75G','Jaune d''oeuf','IgG spécifiques','Composants allergéniques','Origine animale - recombinants','null'),
  ('F75S','Jaune d''oeuf','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F76','A. lactalbumine - protéines du lait','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F76G','A. lactalbumine - protéines du lait','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F76S','A. lactalbumine - protéines du lait','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F77','B.lactoglobuline - protéines du lait','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F77G','B.lactoglobuline - protéines du lait','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F77S','B.lactoglobuline - protéines du lait','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F78','Caséine - protéines du lait','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F78G','Caséine - protéines du lait','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F78S','Caséine - protéines du lait','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F79','Gluten','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F79G','Gluten','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F79S','Gluten','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F7G','Avoine','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F8','Maïs - aliment','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F80','Homard','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F81','Fromage - pâte cuite','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F81G','Fromage (pâte cuite)','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F82','Fromage - fermenté','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F82G','Fromage (fermenté)','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F83','Poulet (viande)','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F83G','Poulet','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('F83S','Poulet','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine animale','null'),
  ('F84','Kiwi','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F84G','Kiwi','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F84S','Kiwi','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F85','Céleri','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F85S','Céleri','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F86','Persil','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F87','Melon','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F88','Mouton','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1205'),
  ('F89','Moutarde','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F8G','Maïs','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F9','Riz - grain entier - pollen','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F90','Malt','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F91','Mangue','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F92','Banane','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F92G','Banane','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F92S','Banane','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F93','Cacao','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F93G','Cacao','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F93S','Cacao','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('F94','Poire','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F95','Pêche','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F96','Avocat','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F96G','Avocat','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F98','f98 Gliadine (blé)','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1205'),
  ('F9G','Riz - grain entier - pollen','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('F9S','Riz','IgG spécifiques sous classes 4','Trophallergènes','Aliments d''origine végétale','null'),
  ('FX1','Noix - Arachide, noisette, noix du Brésil, amande, noix de coco','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX10','Viandes - boeuf, porc, jaune d''oeuf, poulet, dinde','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1202'),
  ('FX11','Légumes - maïs, pois, haricot blanc, carotte, brocoli','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX12','Légumes - seigle, riz, pomme de terre, champignon, potiron','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX13','Légumes - pois, haricot blanc, carotte, pomme de terre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX14','Légumes - tomate, épinard, chou, poivron','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX15','Fruits - orange, pomme, banane, pêche','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX16','Fruits - fraise, poire, citron, ananas','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX17','Fruits - pomme, banane, poire, pêche','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX18','Aliments - pois, arachide, soja','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX19','Légumes - carotte, pomme de terre, épinard, concombre','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX2','Produits de la mer - morue, crevette, thon, saumon, moule','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1202'),
  ('FX20','Céréales - blé, seigle, orge, riz','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX21','Fruits - kiwi, melon, banane, pêche, ananas','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX22','Fruits secs - noix de pécan, noix de cajou, pistache, noix','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX22G','Noix de pécan,noix de cajou,pistache,noix','IgG spécifiques','Trophallergènes','Aliments d''origine végétale','null'),
  ('FX23','Trophatop 3 - porc, boeuf, poulet, dinde','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1202'),
  ('FX24','Trophatop 2 - noisette, crevette, kiwi, banane','IgE spécifiques','Trophallergènes','Origine animale et végétale','1202'),
  ('FX25','Trophatop 4 - sésame, levure de bière, ail, céleri','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX26','Trophatop - blanc d''oeuf, lait, arachide, moutarde','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX27','Trophatop - poisson, noisette, soja, blé','IgE spécifiques','Trophallergènes','Origine animale et végétale','1202'),
  ('FX28','Trophatop  - crevette, kiwi, boeuf, sésame','IgE spécifiques','Trophallergènes','Origine animale et végétale','1202'),
  ('FX29','Mélange - orange, citron, mandarine, pamplemousse','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX3','Farines - blé, avoine, maÏs, sésame, sarrasin','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX30','Fruits - kiwi, mangue, banane, avocat, papaye','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX31','Fruits - pomme, poire, pêche, cerise, prune','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX32','Légumes - lentille, pois, haricot blanc, caroube','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX5','Trophatop  - oeuf, lait de vache, morue, blé, arachide,soja','IgE spécifiques','Trophallergènes','Origine animale et végétale','1202'),
  ('FX7','Légumes - tomate, oignon, ail, levure de bière, céleri','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX70','Aromates - estragon, marjolaine, thym, livèche','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX71','Aromates - cumin, muscade, cardamome, clou de girofle','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX72','Aromates - basilic, fenouil, gingembre, anis','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX73','Viandes - porc, boeuf, poulet','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1202'),
  ('FX74','Poissons - maquereau, hareng, morue, carrelet','IgE spécifiques','Trophallergènes','Aliments d''origine animale','1202'),
  ('FX8','Fruits - pomme, noisette, noix du Brésil, orange, cacao','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('FX9','Fruits exotiques - kiwi, melon, banane, raisin, amande','IgE spécifiques','Trophallergènes','Aliments d''origine végétale','1202'),
  ('G1','Flouve odorante','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G10','Sorgho','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G11','Brome','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G12','Seigle','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G12G','Seigle','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G12S','Seigle','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G13','Houlque laineuse','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G13G','Houlque laineuse','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G14','Avoine - pollen','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G14G','Avoine - pollen-','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G14S','Avoine','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G15','Blé - pollen','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G15G','Blé - pollen','IgG spécifiques','Trophallergènes','Pollens de graminées','null'),
  ('G15S','Blé','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G16','Vulpin des prés','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G16S','Vulpin des prés - Alopecurus pratensis','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G17','Herbe de Bahia','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G1G','Flouve odorante','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G1S','Flouve','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G2','Chiendent digité','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G201','Orge - pollen','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G201S','Orge','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G202','Maïs - pollen','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G202G','Maïs - pollen','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G202S','Maïs - pollen','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G203','Herbe des prés salés','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G204','Fromental','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G205','rPhl p 1 Phléole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G206','rPhl p 2 - Phléole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G208','nPhl p 4 Phéole, natif - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G209','rPhl p 6 Phéole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G210','rPhl p 7 Phéole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G211','rPhl p 11 Phléole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G212','rPhl p 12 Phléole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G213','rPhl p 1, rPhl p 5b Phléole - recombinants','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G213S','rPhl p 1, rPhl p 5b Phléole - recombinants','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G214','rPhl p 7, rPhl p 12 Phléole - recombinants','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G215','rPhl p 5 Phléole - recombinant','IgE spécifiques','Composants allergéniques','Pollens de graminées - recombinants','1204'),
  ('G216','g216 nCyn d 1  (Beta-expansine, chiendent digité)','IgE spécifiques','Composants allergéniques','Origine végétale - recombinants','1204'),
  ('G2G','Chiendent','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G2S','Chiendent','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G3','Dactyle pelotonné','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G3G','Dactyle','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G3S','Dactyle','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G4','Fétuque des prés','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G4G','Fétuque des prés','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G4S','Fétuque des prés','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G5','Ivraie vivace','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G5G','Ivraie','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G5S','Ivraie','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G6','Phléole des prés','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G6G','Phléole des prés','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G6S','Phléole des prés','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G7','Roseau à balais','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G70','Ivraie sauvage','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G71','Alpiste','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G8','Paturin des prés','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G8G','Paturin','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('G8S','Paturin','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('G9','Agrostide','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('G900','Fleur de canne à sucre','IgE spécifiques','Aéroallergènes','Pollens de graminées','1204'),
  ('GF24','f24G Crevette','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('GF290','f290G Huitre','IgG spécifiques','Trophallergènes','Aliments d''origine animale','null'),
  ('GX1','Pollens de graminées - dactyle, fétuque, ivraie, phléole, paturin','IgE spécifiques','Aéroallergènes','Pollens de graminées','1201'),
  ('GX1G','Pollens de graminées (Dactyle, fétuque, ivraie, phléole, paturin)','IgG spécifiques','Aéroallergènes','Pollens de graminées','null'),
  ('GX1S','Pollens de graminées (Dactyle, fétuque, ivraie, phléole, paturin)','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('GX2','Pollens de graminées - chiendent, ivraie, phléole, paturin, sorgho','IgE spécifiques','Aéroallergènes','Pollens de graminées','1201'),
  ('GX3','Pollens de graminées - flouve, ivraie, phléole, seigle, houlque','IgE spécifiques','Aéroallergènes','Pollens de graminées','1201'),
  ('GX3S','Pollens de graminées (Flouve, ivraie, phléole, seigle et houlque)','IgG spécifiques sous classes 4','Aéroallergènes','Pollens de graminées','null'),
  ('GX4','Pollens de graminées - flouve, ivraie, roseau, seigle, houlque','IgE spécifiques','Aéroallergènes','Pollens de graminées','1201'),
  ('GX6','Pollens de graminées - chiendent, ivraie, sorgho, brome, houlque, h. bahia','IgE spécifiques','Aéroallergènes','Pollens de graminées','1201'),
  ('I1','Venin d''abeille','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I1G','Venin d''abeille','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I1S','Venin d''abeille','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I2','Frelon tête blanche','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I201G','Mouche du cheval','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I202','Charançon du blé','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I202G','Sitophilus granarius','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I203','Ephestia','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I204','Taon','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I204G','Taon','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I204S','Taon','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I205','Bourdon','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I205G','Bourdon','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I205S','Bordon','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I206','Blatte américaine','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I206S','Blatte américaine','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I207','Blatte orientale','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I208','rApi,m1,Phospholipase A2 Abeille','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I209','rVes v 5 (Ag 5, vespula vulgaris)','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I210','rPol d 5 (Ag 5, polistes dominulus)','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I211','rVes v 1  (phospholipase A1 - venin de Guêpe Vespula)','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I217','rApi m10 Icarapine Abeille','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I2G','Frelon tête blanche','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I2S','Frelon tête blanche','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I3','Venin de guêpe - vespula','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I3G','Venin de guêpe - vespula','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I3S','Venin de guêpe - vespula','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I4','Venin de guêpe - poliste','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I4G','Venin de guêpe - poliste','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I4S','Venin de guêpe - poliste','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I5','Frelon tête jaune','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I5G','Frelon tête jaune','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I5S','Frelon tête jaune','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I6','Cafard - Blatte germanique','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I6G','Cafard - Blatte germanique','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I6S','Cafard - Blatte germanique','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I70','Fourmi rouge','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I70G','Fourmi rouge','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I70S','Fourmi rouge','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I71','Moustique - aedes communs','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I71G','Moustique','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I71S','Moustique','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I72','Mouche du Soudan','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I72S','Mouche du Soudan','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I73','Larve de ver de vase','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I75','Venin de frelon - Vespa crabro','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I75G','Venin de frelon','IgG spécifiques','Venins et insectes','Venins et insectes','null'),
  ('I75S','Venin de frelon','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I76','Scarabée','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('I77','Venin de guêpe - poliste dominulus','IgE spécifiques','Venins et insectes','Venins et insectes','0967'),
  ('I77S','Venin de guêpe - poliste dominulus','IgG spécifiques sous classes 4','Venins et insectes','Venins et insectes','null'),
  ('I8','Ver à soie - Bombyx mori','IgE spécifiques','Venins et insectes','Venins et insectes','1204'),
  ('K1','Fibre acrylique','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K14','Kapok','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K20','Laine de mouton traitée','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K201','Papaïne','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K202','Bromeline','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K204','Maxatase','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K205','Alkalase','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204'),
  ('K206','Savinase','IgE spécifiques','Allergènes professionnels','Allergènes professionnels','1204');

COMMIT;