START TRANSACTION;

CREATE DATABASE IF NOT EXISTS forza;
SET CHARACTER SET 'utf8';

USE forza;

CREATE TABLE `handicaps` (
  `code_handicap` varchar(255) NOT NULL PRIMARY KEY,
  `designation` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `handicaps` (`code_handicap`, `designation`) VALUES
('F70', 'Retard mental léger'),
('F71', 'Retard mental modéré'),
('F72', 'Retard mental sévère'),
('F73', 'Retard mental profond'),
('F78', 'Autres formes de retard mental'),
('F79', 'Retard mental, sans précision'),
('G00', 'Méningite bactérienne'),
('G01', 'Méningite en maladies bactériennes classées ailleurs'),
('G02', 'Méningite due à d’autres causes et non classée ailleurs'),
('G03', 'Méningite d’étiologie non précisée'),
('G04', 'Encéphalite, myélite et encéphalomyélite'),
('G05', 'Encéphalite, myélite et encéphalomyélite dans des maladies classées ailleurs'),
('G06', 'Abcès intracrânien et intraspinal et granulome'),
('G07', 'Affections inflammatoires du système nerveux central dans des maladies classées ailleurs'),
('G08', 'Phlébite et thrombophlébite intracrâniennes et intraspinales'),
('G09', 'Séquelles de maladies inflammatoires du système nerveux central'),
('G80', 'Infirmité motrice cérébrale'),
('G81', 'Hémiplégie'),
('G82', 'Paraplégie et tétraplégie'),
('F20', 'Schizophrénie paranoïde'),
('F21', 'Schizophrénie hébéphrénique'),
('F22', 'Troubles schizotypiques'),
('F23', 'Troubles psychotiques aigus et transitoires'),
('F24', 'Trouble délirant induit'),
('F25', 'Trouble schizo-affectif'),
('F28', 'Autres troubles psychotiques non organiques'),
('F29', 'Trouble psychotique non organique, sans précision'),
('M15.0', 'Polyarthrite (ostéo)généralisée primitive'),
('M15.1', 'Nodules d’Heberden (avec arthropathie)'),
('M15.2', 'Nodules de Bouchard (avec arthropathie)'),
('M15.3', 'Polyarthrite secondaire'),
('M15.4', 'Polyarthrite (ostéo)érosive'),
('M15.8', 'Autres polyostéoarthrites'),
('M15.9', 'Polyostéoarthrite, sans précision'),
('M50.020', 'Trouble du disque cervical, niveau non précisé'),
('M50.021', 'Trouble du disque cervical au niveau C4-C5 avec myélopathie'),
('M50.022', 'Trouble du disque cervical au niveau C5-C6 avec myélopathie'),
('M50.023', 'Trouble du disque cervical au niveau C6-C7 avec myélopathie'),
('M51.370', 'Dégénérescence discale intervertébrale avec douleur dorsale discogène uniquement'),
('M51.371', 'Dégénérescence discale intervertébrale avec douleur du membre inférieur uniquement'),
('M51.372', 'Dégénérescence discale intervertébrale avec douleur dorsale discogène et douleur du membre inférieur'),
('M51.379', 'Dégénérescence discale intervertébrale sans mention de douleur lombaire ou de douleur du membre inférieur'),
('M51.44', 'Nœuds de Schmorl région thoracique'),
('M51.45', 'Nœuds de Schmorl région thoracolombaire'),
('M51.46', 'Nœuds de Schmorl région lombaire'),
('M51.47', 'Nœuds de Schmorl région lombo-sacrée'),
('M53.2X1', 'Instabilités rachidiennes région occipito-atlanto-axiale'),
('M53.2X3', 'Instabilités rachidiennes région cervico-thoracique'),
('M53.2X2', 'Instabilités rachidiennes région cervicale'),
('M53.2X4', 'Instabilités rachidiennes région thoracique'),
('M53.2X5', 'Instabilités rachidiennes région thoraco-lombaire'),
('M53.2X6', 'Instabilités rachidiennes région lombaire'),
('M53.2X7', 'Instabilités rachidiennes région lombo-sacrée'),
('M53.2X8', 'Instabilités rachidiennes région sacrée et sacro-coccygienne'),
('M53.2X9', 'Instabilités rachidiennes site non précisé'),
('M54', 'Dorsalgie'),
('J45', 'Asthme'),
('J4A.0', 'Syndrome restrictif du greffon'),
('J4A.8', 'Autres dysfonctions chroniques du greffon pulmonaire'),
('J4A.9', 'Dysfonction chronique du greffon pulmonaire'),
('S08.111', 'Amputation traumatique complète de l’oreille droite'),
('S08.112', 'Amputation traumatique complète de l’oreille gauche'),
('S08.81', 'Amputation traumatique du nez'),
('S48.0', 'Amputation traumatique à l’articulation de l’épaule'),
('S48.1', 'Amputation traumatique entre l’épaule et le coude'),
('S48.9', 'Amputation traumatique de l’épaule et du bras, niveau non précisé'),
('S68', 'Amputation traumatique du poignet, de la main et des doigts'),
('S78.01', 'Amputation traumatique complète à l’articulation de la hanche'),
('S78.011', 'Amputation traumatique complète à la hanche droite'),
('S78.012', 'Amputation traumatique complète à la hanche gauche'),
('S78.11', 'Amputation traumatique complète entre la hanche et le genou'),
('S78.111', 'Amputation traumatique complète entre la hanche droite et le genou'),
('S78.112', 'Amputation traumatique complète entre la hanche gauche et le genou'),
('M15', 'Polyostéoarthrite'),
('M16', 'Coxarthrose (arthrose de la hanche)'),
('M17', 'Gonarthrose (arthrose du genou)'),
('M60', 'Myosite'),
('H54.0X', 'Cécité, les deux yeux'),
('H54.41', 'Cécité, œil droit'),
('H54.42', 'Cécité, œil gauche'),
('H25', 'Cataracte liée à l’âge'),
('H40', 'Glaucome'),
('H49', 'Strabisme paralytique'),
('I05.2', 'Sténose mitrale rhumatismale'),
('I06.2', 'Sténose aortique rhumatismale'),
('I07.2', 'Sténose tricuspide rhumatismale'),
('I70', 'Athérosclérose'),
('D82', 'Immunodéficience'),
('G56.0', 'Syndrome du canal carpien'),
('G56.3', 'Lésion du nerf radial'),
('G56.2', 'Lésion du nerf ulnaire'),
('G56.4', 'Causalgie du membre supérieur'),
('K73', 'Hépatite chronique'),
('N18', 'Maladie rénale chronique'),
('M35.0', 'Syndrome de Sjögren'),
('L41', 'Parapsoriasis'),
('L42', 'Pityriasis rosé'),
('L43', 'Lichen plan'),
('E10', 'Diabète de type 1'),
('E11', 'Diabète de type 2'),
('Q90', 'Syndrome de Down'),
('Q91.0', 'Trisomie 18'),
('Q91.4', 'Trisomie 13'),
('Q92.0', 'Trisomie de chromosome entier'),
('Q97.0', 'Caryotype 47'),
('Q97.3', 'Femme avec 46'),
('Q98.0', 'Syndrome de Klinefelter caryotype 47'),
('Q99.2', 'Chromosome X fragile'),
('Q99.9', 'Anomalie chromosomique, sans précision'),
('Q92.2', 'Trisomie partielle'),
('Q93.51', 'Syndrome d’Angelman'),
('Q93.52', 'Syndrome de Phelan-McDermid'),
('Q93.81', 'Syndrome vélo-cardio-facial'),
('Q93.82', 'Syndrome de Williams'),
('Q95.1', 'Inversion chromosomique'),
('C00', 'Tumeur maligne de la lèvre'),
('C01', 'Tumeur maligne de la base de la langue'),
('C03', 'Tumeur maligne de la gencive'),
('C04', 'Tumeur maligne du plancher buccal'),
('C05', 'Tumeur maligne du palais'),
('C07', 'Tumeur maligne de la glande parotide'),
('C09', 'Tumeur maligne de l’amygdale'),
('C10', 'Tumeur maligne de l’oropharynx'),
('C11', 'Tumeur maligne du nasopharynx'),
('C12', 'Tumeur maligne du sinus piriforme'),
('C13', 'Tumeur maligne de l’hypopharynx'),
('C15', 'Tumeur maligne de l’œsophage'),
('C16', 'Tumeur maligne de l’estomac'),
('C17', 'Tumeur maligne de l’intestin grêle'),
('C18', 'Tumeur maligne du côlon'),
('C19', 'Tumeur maligne de la jonction rectosigmoïdienne'),
('C20', 'Tumeur maligne du rectum'),
('C21', 'Tumeur maligne de l’anus'),
('C22', 'Tumeur maligne du foie'),
('C23', 'Tumeur maligne de la vésicule biliaire'),
('C25', 'Tumeur maligne du pancréas'),
('C30', 'Tumeur maligne de la cavité nasale et des sinus'),
('C31', 'Tumeur maligne des sinus accessoires'),
('C32', 'Tumeur maligne du larynx'),
('C33', 'Tumeur maligne de la trachée'),
('C34', 'Tumeur maligne des bronches et du poumon'),
('C37', 'Tumeur maligne du thymus'),
('C38', 'Tumeur maligne du cœur'),
('C40', 'Tumeur maligne des os'),
('C43', 'Mélanome malin de la peau'),
('C45', 'Mésothéliome'),
('C46', 'Sarcome de Kaposi'),
('C47', 'Tumeur maligne des nerfs périphériques'),
('C50', 'Tumeur maligne du sein'),
('C51', 'Tumeur maligne de la vulve'),
('C52', 'Tumeur maligne du vagin'),
('C53', 'Tumeur maligne du col de l’utérus'),
('C54', 'Tumeur maligne du corps de l’utérus'),
('C56', 'Tumeur maligne de l’ovaire'),
('C58', 'Tumeur maligne du placenta'),
('C60', 'Tumeur maligne du pénis'),
('C61', 'Tumeur maligne de la prostate'),
('C62', 'Tumeur maligne du testicule'),
('C64', 'Tumeur maligne du rein'),
('C65', 'Tumeur maligne du bassinet'),
('C66', 'Tumeur maligne de l’uretère'),
('C67', 'Tumeur maligne de la vessie'),
('C69', 'Tumeur maligne de l’œil et des annexes'),
('C70', 'Tumeur maligne des méninges'),
('C71', 'Tumeur maligne du cerveau'),
('C72', 'Tumeur maligne de la moelle épinière'),
('C73', 'Tumeur maligne de la thyroïde'),
('C74', 'Tumeur maligne de la glande surrénale'),
('C7A', 'Tumeurs neuroendocrines malignes'),
('D3A', 'Tumeurs neuroendocrines bénignes');

COMMIT;