START TRANSACTION;

CREATE DATABASE IF NOT EXISTS forza;
SET CHARACTER SET 'utf8';

USE forza;

CREATE TABLE `maladies` (
  `code_maladie` varchar(255) NOT NULL PRIMARY KEY,
  `designation` varchar(255) NOT NULL,
  `chronique` tinyint(1) DEFAULT 0,
  `hereditaire` tinyint(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `maladies` (`code_maladie`, `designation`, `chronique`) VALUES
  ('CA23', 'asthme', 1),
  ('75120Z0', 'Diabètes', 1),
  ('21120Z1', 'Grippe', 0),
  ('98N23ZZ', 'Hypertension', 1),
  ('1A00', 'Choléra', 0),
  ('1A01', 'Infection intestinale due à d’autres Vibrio', 0),
  ('1A02', 'Infections intestinales dues à Shigella', 0),
  ('1A03.0', 'Infection à Escherichia coli entéropathogène', 0),
  ('1A03.1', 'Infection à Escherichia coli entérotoxinogène', 0),
  ('1A03.2', 'Infection à Escherichia coli entéro-invasive', 0),
  ('1A03.3', 'Infection à Escherichia coli entérohémorragique', 0),
  ('1A03.Y', 'Autres infections intestinales à Escherichia coli', 0),
  ('1A03.Z', 'Infections intestinales à Escherichia coli, sans précision', 0),
  ('1A04', 'Infections intestinales dues à Clostridioides difficile', 0),
  ('1A05', 'Infections intestinales dues à Yersinia enterocolitica', 0),
  ('1A06', 'Gastroentérite due à Campylobacter', 0),
  ('1A07', 'Fièvre typhoïde', 0),
  ('1A07.0', 'Péritonite typhoïde', 0),
  ('1A07.Y', 'Autres fièvres typhoïdes', 0),
  ('1A07.Z', 'Fièvre typhoïde, sans précision', 0),
  ('1A08', 'Fièvre paratyphoïde', 0),
  ('1A09', 'Infections dues à d’autres Salmonella', 0),
  ('1A0Y', 'Autres infections intestinales bactériennes', 0),
  ('1A0Z', 'Infections intestinales bactériennes, sans précision', 0),
  ('1A10', 'Intoxication alimentaire à staphylocoques', 0),
  ('1A11.0', 'Intoxication alimentaire par la toxine botulique', 0),
  ('1A11.1', 'Autres formes de botulisme', 0),
  ('1A11.Z', 'Botulisme, sans précision', 0),
  ('1A12', 'Intoxication alimentaire à Clostridium perfringens', 0),
  ('1A13', 'Intoxication alimentaire à Bacillus cereus', 0),
  ('1A1Y', 'Autres intoxications alimentaires d’origine bactérienne', 0),
  ('1A1Z', 'Intoxications alimentaires d’origine bactérienne, sans précision', 0),
  ('1A20', 'Entérite due à Adenovirus', 0),
  ('1A21', 'Gastroentérite due à Astrovirus', 0),
  ('1A22', 'Gastroentérite à Rotavirus', 0),
  ('1A23', 'Entérite à Norovirus', 0),
  ('1A24', 'Infections intestinales dues à Cytomégalovirus', 0),
  ('1A2Y', 'Autres infections intestinales virales', 0),
  ('1A2Z', 'Infections intestinales virales, sans précision', 0),
  ('1A30', 'Infections dues à Balantidium coli', 0),
  ('1A31', 'Giardiase', 0),
  ('1A32', 'Cryptosporidiose', 0),
  ('1A33.1', 'Infection à Isospora du côlon', 0),
  ('1A33.Y', 'Autres cystoisosporoses', 0),
  ('1A33.Z', 'Cystoisosporose, sans précision', 0),
  ('1A34', 'Sarcocystose', 0),
  ('1A35', 'Blastocystose', 0),
  ('1A36.0', 'Infections intestinales à Entamoeba', 0),
  ('1A36.00', 'Amibiase aiguë', 0),
  ('1A36.0Z', 'Infections intestinales à Entamoeba, sans précision', 0),
  ('1A36.1', 'Infections extra-intestinales dues à Entamoeba', 0),
  ('1A36.10', 'Abcès amibien du foie', 0),
  ('1A36.11', 'Abcès amibien du poumon', 0),
  ('1A36.12', 'Amibiase cutanée', 0),
  ('1A36.1Y', 'Autres infections extra-intestinales dues à Entamoeba', 0),
  ('1A36.Z', 'Amibiase, sans précision', 0),
  ('1A3Y', 'Autres infections intestinales à protozoaires', 0),
  ('1A3Z', 'Infections intestinales à protozoaires, sans précision', 0),
  ('1A40.0', 'Gastroentérite ou colite sans origine précisée', 0),
  ('1F23.2', 'Candidose du tractus gastro-intestinal', 0),
  ('1F20.0', 'Aspergillose invasive du tube digestif', 0),
  ('1A60', 'Syphilis congénitale', 0),
  ('1A61', 'Syphilis précoce', 0),
  ('1A62', 'Syphilis tardive', 0),
  ('1A63', 'Syphilis latente, non précisée précoce ou tardive', 0),
  ('1A6Z', 'Syphilis, sans précision', 0),
  ('1A90', 'Chancroïde', 0),
  ('1A91', 'Granulome inguinal', 0),
  ('1A92', 'Trichomonase', 0),
  ('1A93', 'Infestations sexuellement transmissibles', 0),
  ('1G04.0', 'Gale classique', 0),
  ('1G04.1', 'Gale croûteuse', 0),
  ('1G04.Y', 'Autres gale', 0),
  ('1A94', 'Infection herpétique à Herpes simplex', 0),
  ('1A94.0', 'Infection à Herpes simplex des organes génitaux ou du tractus urogénital', 0),
  ('1A94.1', 'Infection à Herpes simplex de la peau périnéale ou du rectum', 0),
  ('1A94.Z', 'Infection herpétique à Herpes simplex, sans précision', 0),
  ('1A95', 'Verrues anogénitales', 0),
  ('1A95.0', 'Verrues anales', 0),
  ('1A95.1', 'Verrues génitales', 0),
  ('1A95.2', 'Condylomes acuminés extragénitaux', 0),
  ('1A95.Z', 'Verrues anogénitales, sans précision', 0),
   ('1B10', 'Tuberculose du système respiratoire', 1),
  ('1B10.0', 'Tuberculose respiratoire confirmée', 1),
  ('1B10.1', 'Tuberculose respiratoire non-confirmée', 1),
  ('1B10.Z', 'Tuberculose respiratoire, sans mention de confirmation bactériologique ou histologique', 1),
  ('1B11', 'Tuberculose du système nerveux', 1),
  ('1B11.0', 'Méningite tuberculeuse', 1),
  ('1B11.1', 'Méningo-encéphalite tuberculeuse', 1),
  ('1B11.2', 'Tuberculome méningé', 1),
  ('1B11.3', 'Granulome tuberculeux du cerveau', 1),
  ('1B11.Y', 'Autres tuberculoses du système nerveux', 1),
  ('1B11.Z', 'Tuberculose du système nerveux, sans précision', 1),
  ('1B12.0', 'Tuberculose cardiaque', 1),
  ('1B12.3', 'Tuberculose des glandes endocrines', 1),
  ('1B12.4', 'Tuberculose du système musculosquelettique', 1),
  ('1B12.40', 'Tuberculose des os ou des articulations', 1),
  ('1B12.41', 'Myosite tuberculeuse', 1),
  ('1B12.4Y', 'Autres tuberculoses du système musculosquelettique', 1),
  ('1B12.4Z', 'Tuberculose du système musculosquelettique, sans précision', 1),
  ('1B12.5', 'Tuberculose du système génito-urinaire', 1),
  ('1B12.6', 'Lymphadénopathie périphérique tuberculeuse', 1),
  ('1B12.7', 'Tuberculose du système digestif', 1),
  ('1B12.8', 'Tuberculose cutanée', 1),
  ('1B13', 'Tuberculose miliaire', 1),
  ('1B13.0', 'Tuberculose miliaire aiguë, localisation unique précisée', 1),
  ('1B13.1', 'Tuberculose miliaire aiguë de localisations multiples', 1),
  ('1B13.2', 'Tuberculose miliaire aiguë, localisation non précisée', 1),
  ('1B13.Y', 'Autres tuberculose miliaire', 1),
  ('1B13.Z', 'Tuberculose miliaire, sans précision', 1),
  ('1B14', 'Tuberculose latente', 1),
  ('KA61.0', 'Tuberculose congénitale', 1),
  ('1C60.0', 'Maladie à VIH stade clinique 1 associée à la tuberculose', 1),
  ('1C60.1', 'Maladie à VIH stade clinique 2 associée à la tuberculose', 1),
  ('1C60.2', 'Maladie à VIH stade clinique 3 associée à la tuberculose', 1),
  ('1C60.3', 'Maladie à VIH stade clinique 4 associée à la tuberculose', 1),
  ('1B1Y', 'Autres tuberculose', 1),
  ('1B1Z', 'Tuberculose, sans précision', 1),
   ('1B20', 'Lèpre', 1),
  ('1B20.0', 'Lèpre paucibacillaire', 1),
  ('1B20.1', 'Lèpre multibacillaire', 1),
  ('1B20.2', 'Réactions de la lèpre', 1),
  ('1B20.3', 'Complications de la lèpre', 1),
  ('1B20.Z', 'Lèpre, sans précision', 1),
  ('1B21', 'Infections à mycobactéries non-tuberculeuses', 1),
  ('1B21.0', 'Infection pulmonaire due à des mycobactéries atypiques', 1),
  ('1B21.1', 'Lymphadénite à mycobactéries atypiques', 1),
  ('1B21.2', 'Infection cutanée à mycobactéries atypiques', 1),
  ('1B21.3', 'Infection disséminée à mycobactéries atypiques', 1),
  ('1B21.4', 'Infection gastro-intestinale à mycobactéries atypiques', 1),
  ('1B21.Z', 'Infection mycobactérienne non tuberculeuse de site non précisé', 1),
  ('1B2Y', 'Autres maladies mycobactériennes', 1),
  ('1B2Z', 'Maladies mycobactériennes, sans précision', 1),
  ('1B50', 'Scarlatine', 0),
  ('1B51', 'Pharyngite à streptocoques', 0),
  ('1B53', 'Méningite due aux streptocoques', 0),
  ('1B54', 'Méningite due aux staphylocoques', 0),
  ('1B70', 'Cellulite bactérienne, érysipèle ou lymphangite', 0),
  ('1B70.0', 'Érysipèle', 0),
  ('1B70.1', 'Cellulite streptococcique de la peau', 0),
  ('1B70.2', 'Cellulite staphylococcique de la peau', 0),
  ('1B70.3', 'Lymphangite bactérienne ascendante', 0),
  ('1B70.Z', 'Cellulite bactérienne, érysipèle ou lymphangite due à un agent bactérien non précisé', 0),
  ('1B71', 'Fasciite nécrosante', 0),
  ('1B71.0', 'Fasciite nécrosante à streptocoque', 0),
  ('1B71.1', 'Fasciite nécrosante polymicrobienne', 0),
  ('1B71.2', 'Fasciite nécrosante néonatale', 0),
  ('1B71.Y', 'Autres fasciite nécrosante', 0),
  ('1B71.Z', 'Fasciite nécrosante, sans précision', 0),
  ('1B72', 'Impétigo', 0),
  ('1B72.0', 'Impétigo bulleux', 0),
  ('1B72.1', 'Impétigo non-bulleux', 0),
  ('1B72.Y', 'Autres impétigo', 0),
  ('1B72.Z', 'Impétigo, sans précision', 0),
  ('1B73', 'Ecthyma', 0),
  ('1B73.0', 'Ecthyma à streptocoque', 0),
  ('1B73.1', 'Ecthyma staphylococcique', 0),
  ('1B73.2', 'Ecthyma gangreneux', 0),
  ('1B73.Y', 'Autres ecthyma', 0),
  ('1B73.Z', 'Ecthyma, sans précision', 0),
  ('1B74', 'Folliculite bactérienne superficielle', 0),
  ('1B74.0', 'Folliculite superficielle à Staphylococcus aureus', 0),
  ('1B74.Y', 'Autres folliculite bactérienne superficielle', 0),
  ('1B74.Z', 'Folliculite bactérienne superficielle, sans précision', 0),
  ('1B75', 'Folliculite bactérienne profonde ou abcès pyogénique de la peau', 0),
  ('1B75.0', 'Furoncle', 0),
  ('1B75.1', 'Anthrax', 0),
  ('1B75.2', 'Furonculose', 0),
  ('1B75.3', 'Abcès pyogénique de la peau', 0),
  ('1B75.4', 'Folliculite bactérienne profonde chronique', 0),
  ('1B75.Z', 'Folliculite bactérienne profonde ou abcès pyogénique de la peau, sans précision', 0),
  ('EE12.0', 'Paronychie bactérienne aiguë', 0),
  ('1B77', 'Autres infections bactériennes pyogènes de la peau ou des tissus sous-cutanés', 0),
  ('1B7Z', 'Infections bactériennes pyogènes de la peau et des tissus sous-cutanés, sans précision', 0),
  ('1B90', 'Fièvres causées par morsure de rat', 0),
  ('1B90.0', 'Spirillose', 0),
  ('1B90.1', 'Streptobacillose', 0),
  ('1B91', 'Leptospirose', 0),
  ('1B92', 'Morve', 0),
  ('1B93', 'Peste', 0),
  ('1B93.0', 'Peste bubonique', 0),
  ('1B93.1', 'Peste cutanée', 0),
  ('1B93.2', 'Peste pneumonique', 0),
  ('1B93.3', 'Peste méningée', 0),
  ('1B93.Y', 'Autres peste', 0),
  ('1B93.Z', 'Peste, sans précision', 0),
  ('1B94', 'Tularémie', 0),
  ('1B94.0', 'Tularémie ulcéroglangulaire', 0),
  ('1B94.Y', 'Autres tularémies précisées', 0),
  ('1B94.Z', 'Tularémie, sans précision', 0),
  ('1B95', 'Brucellose', 0),
  ('1B96', 'Érysipéloïde', 0),
  ('1B97', 'Anthrax', 0),
  ('1B98', 'Maladie des griffes du chat', 0),
  ('1B99', 'Pasteurellose', 0),
  ('1B9Z', 'Certaines anthropozoonoses bactériennes précisées, sans précision', 0),
  ('1C10', 'Actinomycose', 0),
  ('1C10.0', 'Actinomycose pulmonaire', 0),
  ('1C10.1', 'Actinomycose abdominale', 0),
  ('1C10.2', 'Actinomycose cervicofaciale', 0),
  ('1C10.3', 'Actinomycose cutanée primaire', 0),
  ('1C10.Y', 'Autres actinomycose', 0),
  ('1C10.Z', 'Actinomycose, sans précision', 0),
  ('1C11', 'Bartonellose', 0),
  ('1C11.0', 'Maladie de Carrión', 0),
  ('1C11.00', 'Fièvre Oroya', 0),
  ('1C11.1', 'Fièvre des tranchées', 0),
  ('1C11.Y', 'Autres bartonelloses', 0),
  ('1C11.Z', 'Bartonellose, sans précision', 0),
  ('1C12', 'Coqueluche', 0),
  ('1C12.0', 'Coqueluche à Bordetella pertussis', 0),
  ('1C12.1', 'Coqueluche à Bordetella parapertussis', 0),
  ('1C12.Y', 'Autres coqueluche', 0),
  ('1C12.Z', 'Coqueluche, sans précision', 0),
  ('1C13', 'Tétanos', 0),
  ('1C14', 'Tétanos obstétrique', 0),
  ('1C15', 'Tétanos néonatal', 0),
  ('1C16', 'Gangrène gazeuse', 0),
  ('1C17', 'Diphtérie', 0),
  ('1C17.0', 'Diphtérie pharyngée ou amygdalienne', 0),
  ('1C17.1', 'Diphtérie nasale', 0),
  ('1C17.2', 'Diphtérie laryngée', 0),
  ('1C17.3', 'Diphtérie cutanée', 0),
  ('1C17.Y', 'Autres diphtérie', 0),
  ('1C17.Z', 'Diphtérie, sans précision', 0),
  ('1C18', 'Fièvre purpurique brésilienne', 0),
  ('1C19', 'Légionellose', 0),
  ('1C19.0', 'Légionellose non pneumonique', 0),
  ('1C19.1', 'Maladie des légionnaires', 0),
  ('1C19.Z', 'Légionellose, sans précision', 0),
  ('1C1A', 'Listériose', 0),
  ('1C1A.0', 'Listériose cutanée', 0),
  ('1C1A.1', 'Méningite ou méningoencéphalite listérienne', 0),
  ('1C1A.Y', 'Autres listériose', 0),
  ('1C1A.Z', 'Listériose, sans précision', 0),
  ('1C1B', 'Nocardiose', 0),
  ('1C1B.0', 'Nocardiose pulmonaire', 0),
  ('1C1B.1', 'Nocardiose cutanée', 0),
  ('1C1B.Y', 'Autres nocardiose', 0),
  ('1C1B.Z', 'Nocardiose, sans précision', 0),
  ('1C1C', 'Méningococcie', 0),
  ('1C1C.0', 'Méningite à méningocoques', 0),
  ('1C1C.1', 'Syndrome de Waterhouse-Friderichsen', 0),
  ('1C1C.2', 'Méningococcémie', 0),
  ('1C1C.20', 'Méningococcémie aiguë', 0),
  ('1C1C.2Y', 'Autres méningococcémie', 0),
  ('1C1C.2Z', 'Méningococcémie, sans précision', 0),
  ('1C1C.Y', 'Autres méningococcie', 0),
  ('1C1C.Z', 'Méningococcie, sans précision', 0),
  ('1C1D', 'Pian', 0),
  ('1C1D.0', 'Pian primaire', 0),
  ('1C1D.1', 'Pian secondaire', 0),
  ('1C1D.2', 'Pian tertiaire', 0),
  ('1C1D.3', 'Pian latent', 0),
  ('1C1D.Z', 'Pian, sans précision', 0),
  ('1C1E', 'Pinta', 0),
  ('1C1E.0', 'Lésions primaires de pinta', 0),
  ('1C1E.1', 'Lésions intermédiaires de pinta', 0),
  ('1C1E.2', 'Lésions tardives de pinta', 0),
  ('1C1E.3', 'Lésions mixtes de pinta', 0),
  ('1C1E.Z', 'Pinta, sans précision', 0),
  ('1C1F', 'Syphilis endémique non-vénérienne', 0),
  ('1C1G', 'Borréliose de Lyme', 0),
  ('1C1G.0', 'Borréliose de Lyme cutanée précoce', 0),
  ('1C1G.10', 'Neuroborréliose de Lyme', 0),
  ('1C1G.11', 'Cardite de Lyme', 0),
  ('1C1G.12', 'Borréliose ophtalmique de Lyme', 0),
  ('1C1G.13', 'Arthrite de Lyme', 0),
  ('1C1G.14', 'Borréliose cutanée tardive de Lyme', 0),
  ('1C1G.1Y', 'Autres borréliose de Lyme disséminée', 0),
  ('1C1G.1Z', 'Borréliose de Lyme disséminée, sans précision', 0),
  ('1C1G.Y', 'Autres borréliose de Lyme précisées', 0),
  ('1C1G.Z', 'Borréliose de Lyme, sans précision', 0),
  ('1C1H', 'Gingivite ulcéronécrosante', 0),
  ('1C1H.0', 'Autres infections de Vincent', 0),
  ('1C1H.Y', 'Autres gingivite ulcéronécrosante', 0),
  ('1C1H.Z', 'Gingivite ulcéronécrosante, sans précision', 0),
  ('1C1J', 'Fièvre récurrente', 0),
  ('1C1J.0', 'Fièvre récurrente transmise par les tiques', 0),
  ('1C1J.1', 'Fièvre récurrente transmise par les poux', 0),
  ('1C1J.Z', 'Fièvre récurrente, sans précision', 0),
  ('1C20', 'Conjonctivite à Chlamydia', 0),
  ('1C21', 'Péritonite à Chlamydia', 0),
  ('1C22', 'Infections à Chlamydia psittaci', 0),
  ('1C23', 'Trachome', 0),
  ('1C23.0', 'Stade initial du trachome', 0),
  ('1C23.1', 'Stade actif du trachome', 0),
  ('1C23.Y', 'Autres trachome', 0),
  ('1C23.Z', 'Trachome, sans précision', 0),
  ('1C2Y', 'Autres maladies dues à Chlamydia', 0),
  ('1C2Z', 'Autres maladies dues à Chlamydia, sans précision', 0),
  ('1C30', 'Typhus', 0),
  ('1C30.0', 'Typhus épidémique à poux dû à Rickettsia prowazekii', 0),
  ('1C30.1', 'Typhus résurgent', 0),
  ('1C30.2', 'Typhus dû à Rickettsia typhi', 0),
  ('1C30.3', 'Typhus à Orientia tsutsugamushi', 0),
  ('1C30.Y', 'Autres typhus', 0),
  ('1C30.Z', 'Typhus, sans précision', 0),
  ('1C31', 'Fièvre pourprée', 0),
  ('1C31.0', 'Fièvre pourprée due à Rickettsia rickettsii', 0),
  ('1C31.1', 'Fièvre pourprée due à Rickettsia conorii', 0),
  ('1C31.2', 'Fièvre pourprée due à Rickettsia sibirica', 0),
  ('1C31.3', 'Fièvre pourprée due à Rickettsia australis', 0),
  ('1C31.Y', 'Autres fièvre pourprée', 0),
  ('1C31.Z', 'Fièvre pourprée, sans précision', 0),
  ('1C32', 'Rickettsiose varicelliforme due à Rickettsia akari', 0),
  ('1C33', 'Fièvre Q', 0),
  ('1C33.Y', 'Autres rickettsioses précisées', 0),
  ('1C33.Z', 'Rickettsioses, sans précision', 0),
  ('1C40', 'Campylobactériose', 0),
  ('1C41', 'Infection bactérienne de localisation non précisée', 0),
  ('1C42', 'Mélioïdose', 0),
  ('1C43', 'Actinomycétome', 0),
  ('1C44', 'Infections bactériennes non-pyogènes de la peau', 0),
  ('1C45', 'Syndrome du choc toxique', 0),
  ('1C45.0', 'Syndrome du choc toxique streptococcique', 0),
  ('1C45.1', 'Syndrome du choc toxique staphylococcique', 0),
  ('1C45.Y', 'Autres syndrome du choc toxique', 0),
  ('1C45.Z', 'Syndrome du choc toxique, sans précision', 0),
  ('1C4Y', 'Autres maladies bactériennes précisées', 0),
  ('1C4Z', 'Autres maladies bactériennes, sans précision', 0),
  ('1C60.0', 'Maladie à VIH stade clinique 1 associée à la tuberculose', 1),
  ('1C60.1', 'Maladie à VIH stade clinique 2 associée à la tuberculose', 1),
  ('1C60.2', 'Maladie à VIH stade clinique 3 associée à la tuberculose', 1),
  ('1C60.3', 'Maladie à VIH stade clinique 4 associée à la tuberculose', 1),
  ('1C80', 'Encéphalite virale, non classée ailleurs', 0),
  ('1C81', 'Poliomyélite aiguë', 0),
  ('1C82', 'Rage', 0),
  ('1C83', 'Encéphalite équine occidentale', 0),
  ('1C84', 'Encéphalite équine orientale', 0),
  ('1C85', 'Encéphalite japonaise', 0),
  ('1C86', 'Encéphalite de St Louis', 0),
  ('1C87', 'Encéphalite à virus de Rocio', 0),
  ('1C88', 'Encéphalite de la Murray Valley', 0),
  ('1C8B', 'Encéphalite de Californie', 0),
  ('1C8C', 'Encéphalite équine vénézuélienne', 0),
  ('1C8D', 'Encéphalite de La Crosse', 0),
  ('1C8E', 'Méningite virale, non classée ailleurs', 0),
  ('1C8F', 'Chorioméningite lymphocytaire', 0),
  ('1C8G', 'Encéphalite à tiques', 0),
  ('1C8Y', 'Autres infections virales du système nerveux central', 0),
  ('1C8Z', 'Infections virales du système nerveux central, sans précision', 0),
  ('1D00', 'Encéphalite infectieuse, non classée ailleurs', 0),
  ('1D00.0', 'Encéphalite bactérienne', 0),
  ('1D00.1', 'Encéphalite fongique', 0),
  ('1D00.2', 'Encéphalite parasitaire ou à protozoaire', 0),
  ('1D00.Y', 'Autres encéphalite infectieuse, non classée ailleurs', 0),
  ('1D00.Z', 'Encéphalite infectieuse, non classée ailleurs, sans précision', 0),
  ('1D01', 'Méningite infectieuse, non classée ailleurs', 0),
  ('1D01.0', 'Méningite bactérienne', 0),
  ('1D01.1', 'Méningite fongique', 0),
  ('1D01.2', 'Méningite parasitaire ou à protozoaire', 0),
  ('1D01.3', 'Méningite récurrente bénigne', 0),
  ('1D01.Y', 'Autres méningites infectieuses non classées ailleurs', 0),
  ('1D01.Z', 'Méningite infectieuse, non classée ailleurs, sans précision', 0),
  ('1D02', 'Myélite infectieuse, non classée ailleurs', 0),
  ('1D02.0', 'Myélite bactérienne', 0),
  ('1D02.1', 'Myélite virale', 0),
  ('1D02.2', 'Myélite fongique', 0),
  ('1D02.3', 'Myélite parasitaire', 0),
  ('1D02.Y', 'Autres myélites infectieuses, non classées ailleurs', 0),
  ('1D02.Z', 'Myélite infectieuse, non classée ailleurs, sans précision', 0),
  ('1D03', 'Abcès infectieux du système nerveux central', 0),
  ('1D03.0', 'Abcès intrarachidien intramédullaire', 0),
  ('1D03.1', 'Abcès intrarachidien sousdural', 0),
  ('1E30', 'Grippe due à un virus grippal saisonnier identifié', 0),
  ('1E31', 'Grippe due à un virus zoonotique ou pandémique identifié', 0),
  ('1E32', 'Grippe, virus non identifié', 0),
  ('1E50', 'Hépatite virale aiguë', 0),
  ('1E51', 'Hépatite virale chronique', 1),
  ('1E51.0', 'Hépatite B chronique', 1),
  ('1E51.1', 'Hépatite C chronique', 1),
  ('1E51.2', 'Hépatite D chronique', 1),
  ('1E51.3', 'Hépatite chronique E', 1),
  ('1E51.Y', 'Autres hépatite virale chronique', 1),
  ('1E51.Z', 'Hépatite virale chronique, sans précision', 1),
  ('1E5Z', 'Hépatite virale, sans précision', 0),
  ('1F20', 'Aspergillose', 0),
  ('1F21', 'Basidiobolomycose', 0),
  ('1F22', 'Blastomycose', 0),
  ('1F23', 'Candidose', 0),
  ('1F23.0', 'Candidose des lèvres ou de la muqueuse buccale', 0),
  ('1F23.1', 'Candidose de la peau ou des muqueuses', 0),
  ('1F23.2', 'Candidose du tractus gastro-intestinal', 0),
  ('1F25', 'Coccidioïdomycose', 0),
  ('1F26', 'Conidiobolomycose', 0),
  ('1F27', 'Cryptococcose', 0),
  ('1F28', 'Dermatophytose', 0),
  ('1F29', 'Eumycétome', 0),
  ('1F2A', 'Histoplasmose', 0),
  ('1F2B', 'Lobomycose', 0),
  ('1F2C', 'Mucormycose, sans précision', 0),
  ('1F2D', 'Dermatomycoses superficielles non dermatophytiques', 0),
  ('1F2E', 'Paracoccidioïdomycose', 0),
  ('1F2F', 'Phaeohyphomycose', 0),
  ('1F2G', 'Pneumocystose', 0),
  ('1F2H', 'Scédosporiose', 0),
  ('1F2J', 'Sporotrichose', 0),
  ('1F2K', 'Talaromycose', 0),
  ('1F2L', 'Emmonsiose', 0),
  ('1F2Y', 'Autres infections dues à des champignons', 0),
  ('1F2Z', 'Infections dues à des champignons, sans précision', 0),
  ('2A00', 'Tumeurs primitives du cerveau', 1),
  ('2A00.0', 'Gliomes du cerveau', 1),
  ('2A00.00', 'Glioblastome du cerveau', 1),
  ('2A00.0Y', 'Autres gliomes du cerveau', 1),
  ('2A00.0Z', 'Gliomes du cerveau, sans précision', 1),
  ('2A00.1', 'Tumeurs embryonnaires du cerveau', 1),
  ('2A00.10', 'Médulloblastome du cerveau', 1),
  ('2A00.11', 'Tumeur neuroectodermique primitive centrale', 1),
  ('2A00.1Y', 'Autres tumeurs embryonnaires du cerveau', 1),
  ('2A00.1Z', 'Tumeurs embryonnaires du cerveau, sans précision', 1),
  ('2A00.2', 'Tumeurs du tissu neuroépithélial du cerveau', 1),
  ('2A00.20', 'Tumeurs de la glande pinéale ou de la région pinéale', 1),
  ('2A00.21', 'Tumeurs mixtes neuronales-gliales', 1),
  ('2A00.22', 'Tumeurs des plexus choroïdes', 1),
  ('2A00.2Y', 'Autres tumeurs du tissu neuroépithélial du cerveau', 1),
  ('2A00.2Z', 'Tumeurs du tissu neuroépithélial du cerveau, sans précision', 1),
  ('2A00.3', 'Neurocytome central du cerveau', 1),
  ('2A00.4', 'Astroblastome du cerveau', 1),
  ('2A00.5', 'Tumeur primitive du cerveau de type inconnu ou non précisé', 1),
  ('2A01', 'Tumeurs primitives des méninges', 1),
  ('2A02.1', 'Tumeurs des nerfs crâniens ou paraspinaux', 1),
  ('2A02.2', 'Tumeur primitive de la moelle épinière de type inconnu ou non précisé', 1),
  ('2A02.3', 'Tumeur bénigne des nerfs crâniens', 1),
  ('2A02.4', 'Tumeur bénigne de la moelle épinière', 1),
  ('2A0Z', 'Tumeurs du cerveau ou du système nerveux central, sans précision', 1),
  ('3A00', 'Anémie par carence en fer', 1),
  ('3A00.0', 'Anémie ferriprive acquise due à une perte de sang', 1),
  ('3A00.1', 'Anémie ferriprive acquise due à un faible apport', 1),
  ('3A00.3', 'Anémie ferriprive acquise due à une augmentation des besoins', 1),
  ('3A00.Y', 'Autres anémie par carence en fer', 1),
  ('3A00.Z', 'Anémie par carence en fer sans précision', 1),
  ('3A01', 'Anémie mégaloblastique due à une carence en vitamine B12', 1),
  ('3A01.0', 'Anémie par carence héréditaire en vitamine B12', 1),
  ('3A01.1', 'Anémie par carence en vitamine B12 néonatale', 1),
  ('3A01.2', 'Anémie par carence en vitamine B12 due à un faible apport', 1),
  ('3A01.3', 'Anémie par carence en vitamine B12 due à un déficit en facteur intrinsèque', 1),
  ('3A01.4', 'Anémie par carence en vitamine B12 due à une maladie intestinale', 1),
  ('3A01.Y', 'Autres anémie mégaloblastique due à une carence en vitamine B12', 1),
  ('3A01.Z', 'Anémie mégaloblastique due à une carence en vitamine B12, sans précision', 1),
  ('3A02', 'Anémie par carence en acide folique', 1),
  ('3A03', 'Autres anémies nutritionnelles ou métaboliques', 1),
  ('3A10', 'Anémie hémolytique héréditaire', 1),
  ('3A1Y', 'Autres anémies hémolytiques congénitales', 1),
  ('3A20', 'Anémie hémolytique acquise, immune', 1),
  ('3A21', 'Anémie hémolytique acquise, non-immune', 1),
  ('3A2Z', 'Anémie hémolytique acquise, sans précision', 1),
  ('3A4Z', 'Anémies hémolytiques, sans précision', 1),
  ('3A50', 'Thalassémies', 1),
  ('3A51', 'Troubles de la drépanocytose ou autres hémoglobinopathies', 1),
  ('3A60', 'Aplasie médullaire congénitale pure des globules rouges', 1),
  ('3A61', 'Aplasie médullaire acquise pure des globules rouges', 1),
  ('3A6Z', 'Aplasie érythrocytaire pure, sans précision', 1),
  ('3A70', 'Aplasie médullaire', 1),
  ('3A70.0', 'Aplasie médullaire congénitale', 1),
  ('3A70.1', 'Aplasies médullaires acquises', 1),
  ('3A70.Z', 'Aplasie médullaire, sans précision', 1),
  ('3A71', 'Anémie due à une maladie chronique', 1),
  ('3A72', 'Anémie sidéroblastique', 1),
  ('3A73', 'Anémie dyserythropoïétique congénitale', 1),
  ('3A90', 'Anémie due à une maladie aiguë', 1),
  ('3A91', 'Méthémoglobinémie congénitale', 1),
  ('3A92', 'Méthémoglobinémie héréditaire', 1),
  ('3A93', 'Méthémoglobinémie acquise', 1),
  ('3A94', 'Anémie posthémorragique aiguë', 1),
  ('3A9Y', 'Autres anémies ou troubles érythrocytaires précisés', 1),
  ('3A9Z', 'Anémies ou autres troubles érythrocytaires, sans précision', 1),
  ('3B60', 'Purpura non-thrombocytopénique', 1),
  ('3B61', 'Thrombophilie', 1),
  ('3B62', 'Anomalies qualitatives des plaquettes', 1),
  ('3B63', 'Thrombocytose', 1),
  ('3B64', 'Thrombocytopénie', 1),
  ('3B65', 'Microangiopathie thrombotique, non classée ailleurs', 1),
  ('4A20', 'Déficits immunitaires acquis', 1),
  ('4A40', 'Lupus érythémateux', 1),
  ('4A41', 'Myopathie inflammatoire idiopathique', 1),
  ('4A42', 'Sclérose systémique', 1),
  ('4A43', 'Maladie auto-immune systémique de chevauchement ou indifférenciée non spécifique à un organe', 1),
  ('4A44', 'Vascularite', 1),
  ('4A45', 'Syndrome des antiphospholipides', 1),
  ('4A60', 'Syndromes auto-inflammatoires monogéniques', 1),
  ('4A61', 'Syndrome SAPHO', 1),
  ('4A62', 'Maladie de Behçet', 1),
  ('4A6Y', 'Autres troubles auto-inflammatoires', 1),
  ('4A6Z', 'Troubles auto-inflammatoires, sans précision', 1),
  ('4A80', 'Troubles allergiques ou dhypersensibilité intéressant les voies respiratoires', 1),
  ('4A81', 'Troubles allergiques ou dhypersensibilité intéressant les yeux', 1),
  ('4A82', 'Troubles allergiques ou dhypersensibilité de la peau ou des muqueuses', 1),
  ('4A83', 'Troubles allergiques ou dhypersensibilité du tractus gastro-intestinal', 1),
  ('4A84', 'Anaphylaxie', 1),
  ('4A85', 'Affections complexes dallergie ou dhypersensibilité', 1),
  ('4B00', 'Anomalies du taux de neutrophiles', 1),
  ('4B01', 'Anomalies fonctionnelles des neutrophiles', 1),
  ('4B02', 'Éosinopénie', 1),
  ('4B03', 'Éosinophilie', 1),
  ('4B04', 'Diminution anormale du taux de monocytes', 1),
  ('4B05', 'Augmentation anormale du taux de monocytes', 1),
  ('4B06', 'Lymphopénie acquise', 1),
  ('4B07', 'Lymphocytose acquise', 1),
  ('4B4Y', 'Autres maladies précisées du système immunitaire', 1),
  ('4B4Z', 'Maladies du système immunitaire, sans précision', 1),
  ('6A60', 'Trouble bipolaire de type I', 1),
  ('6A61', 'Trouble bipolaire de type II', 1),
  ('6A62', 'Trouble cyclothymique', 1),
  ('6A6Y', 'Autres troubles bipolaires ou apparentés', 1),
  ('6A6Z', 'Troubles bipolaires ou apparentés, sans précision', 1),
  ('EA00', 'Exanthème viral dû à un agent inconnu ou non précisé', 1),
  ('1F03.0', 'Rougeole sans complication', 1),
  ('1F02.2', 'Rubéole sans complication', 1),
  ('1F01', 'Exanthème subit', 1),
  ('1F04', 'Mégalérythème épidémique', 1),
  ('1F05.0', 'Stomatite vésiculaire due à un entérovirus', 1),
  ('1F05.3', 'Fièvre aphteuse', 1),
  ('1F05', 'Infections à Picornavirus se manifestant au niveau de la peau ou des muqueuses', 1),
  ('EA0Y', 'Autres exanthèmes viraux', 1),
  ('15', 'Maladies du système musculosquelettique ou du tissu conjonctif',0),
  ('17', 'Affections liées à la santé sexuelle',0),
  ('18', 'Grossesse, accouchement ou puerpéralité',0),
  ('20', 'Anomalies du développement'),
  ('22', 'Lésions traumatiques, intoxications ou certaines autres conséquences de causes externes'),
  ('23', 'Causes externes de morbidité ou de mortalité'),
  ('RA01', 'COVID-19', 1),
  ('RA01.0', 'COVID-19, virus identifié', 1),
  ('RA01.1', 'COVID-19, virus non identifié', 1),
  ('RA02', 'Affection post-COVID-19', 1),
  ('RA03', 'Syndrome inflammatoire multisystémique associé à la COVID-19', 1),
  ('RA04', 'Code international durgence 05', 0),
  ('RA05', 'Code international durgence 06', 0),
  ('RA06', 'Code international durgence 07', 0),
  ('RA07', 'Code international durgence 08', 0),
  ('RA08', 'Code international durgence 09', 0),
  ('RA09', 'Code international durgence 10', 0);
COMMIT;