START TRANSACTION;

CREATE DATABASE IF NOT EXISTS forza;
SET CHARACTER SET 'utf8';

USE forza;

CREATE TABLE `medicaments` (
  `code_medicament` varchar(255) NOT NULL,
  `DCI` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO medicaments (DCI,code_medicament) VALUES
('Paracetamol', 'N02BE01'),
('Propranolol', 'C07AB02'),
('Omeprazole', 'A02BC01'),
('Chlorhexidine', 'A01AB03'),
('Metformine', 'A10BA02'),
('Aspirine', 'B01AC06'),
('Enalapril', 'C09AA05'),
('Simvastatine', 'C10AA05'),
('Betamethasone', 'D07AC13'),
('Ethinylestradiol et Lévonorgestrel', 'G03AA07'),
('Hydrocortisone', 'H02AB04'),
('Amoxicilline', 'J01CA04'),
('Methotrexate', 'L01BC02'),
('Ibuprofène', 'M01AE01'),
('Diazepam', 'N05BA06'),
('Fluoxetine', 'N06AB03'),
('Salbutamol', 'R03AC02'),
('Tétracycline', 'S01AA01'),
('Acide folinique', 'V03AB25'),
('Ciprofloxacine', 'J01MA02'),
('Furosémide', 'C03CA01'),
('Atorvastatine', 'C10AA05'),
('Captopril', 'C09AA01'),
('Lisinopril', 'C09AA03'),
('Composés de magnésium', 'XM7GM7'),
('Hydroxyde de magnésium', 'XM39M3'),
('Aluminium, Silicate daluminium et de magnésium', 'XM35X7'),
('Peroxyde de magnésium', 'XM3CD3'),
('Composés daluminium', 'XM3JP8'),
('Alginate', 'XM9N47'),
('Aluminium, phosphate daluminium', 'XM2VU8'),
('Aloglutamol', 'XM4NY5'),
('Aluminium, glycinate daluminium', 'XM7DC3'),
('Carbonate de sodium dihydroxyaluminum', 'XM9PG0'),
('Gels dhydroxyde daluminium', 'XM38T8'),
('Composés de calcium', 'XM0SA0'),
('Combinaisons et complexes de composés daluminium, de calcium et de magnésium', 'XMOD52'),
('Oxyde de magnésium', 'XM7G33'),
('Cimétidine', 'XM9YL4'),
('Famotidine', 'XM6441'),
('Nizatidine', 'XM9ZP3'),
('Ranitidine', 'XM6WY8'),
('Roxatidine', 'XM0SH0'),
('Nipérotidine', 'XM08A8'),
('Ranitidine citrate de bismuth', 'XM1ZT1'),
('Fénovitidine', 'XMOQ37'),
('Oméprazole', 'XM2WX5'),
('Pantoprazole', 'XM86M3'),
('Lansoprazole', 'XM39X4'),
('Rabéprazole', 'XM3M01'),
('Esoméprazole', 'XM8YE1'),
('Dexlansoprazole', 'XM5RA0'),
('Dexrabéprazole', 'XM1J18'),
('Tegoprazan', 'XM3MK2'),
('Misoprostol', 'XM28N9'),
('Enprostil', 'XM4GD1'),
('Alprostadil', 'XM1CF2'),
('Dinoprostone', 'XM3Q43'),
('Dinoprost', 'XM5VF9'),
('Géméprost', 'XM2L11'),
('Carboprost', 'XM8XM0'),
('Sulprostone', 'XM9BJ7'),
('Carbénoxolone', 'XM2H82'),
('Sucralfate', 'XM0044'),
('Pirenzépine', 'XM6690'),
('Proglumide', 'XM6WX3'),
('Géfarnate', 'XM0HB8'),
('Sulglicotide', 'XM2689'),
('Acide alginique', 'XM4H50'),
('Réframipide', 'XM2891'),
('Chlorure de méthiosulfonium', 'XMF1F15'),
('Souscitrate de bismuth', 'XM1BG6'),
('Acétoxolone', 'XM1LT9'),
('Zolimidine', 'XM9SW3'),
('Troxipide', 'XM1Y11'),
('Sous-nitrate de bismuth', 'XM84X1'),
('Association fixe pour l’éradication d’Helicobacter pylori', 'XM1364'),
('Ondansétron', 'XM7423'),
('Granisétron', 'XM8123'),
('Cilansétron', 'XMA3X37'),
('Dronabinol', 'XM1W83'),
('Nabilone', 'XM3UF9'),
('Diisopromine', 'XM2493'),
('Chlorbenzoxamine', 'XM30Q8'),
('Pinaverium', 'XM2GC8'),
('Fenoverine', 'XM3CZ9'),
('Alvérine', 'XM5RS2'),
('Isométhéptène', 'XM27M9'),
('Migalastat', 'XM6UH6'),
('Fenpiprane', 'XM49K4'),
('Idanpramine', 'XM7FT16'),
('Proxazole', 'XM8N97'),
('Trépibutone', 'XM2SK3'),
('Caroverine', 'XM5R52'),
('Phloroglucinol', 'XM66E5'),
('Triméthyldiphénylpropylamine', 'XM7ZC5'),
('Bromure de valéthamate', 'XM9K48'),
('Aluminium, tannate d’aluminium', 'XMGQ06'),
('Amylopectine', 'XM62S7'),
('Médicaments absorbants d’antidiarrhéique', 'XM8A95'),
('Attapulgite', 'XM6V74'),
('Bacillus subtilis', 'XM4SG9'),
('Sous-carbonate de Bismuth', 'XM98L3'),
('Sels de bismuth', 'XM5U61'),
('Carbo medicinalis', 'XM3962'),
('Charbon', 'XM0SA2'),
('Charbon activé', 'XM46T5'),
('Médicament au charbon (activé)', 'XM22G9'),
('Charbon médicinal, antidiarrhéique', 'XM8D61'),
('Difénoxine', 'XM8ET0'),
('Foetoxilate', 'XM15K3'),
('Médicament régulateur de la motilité intestinale', 'XM3ZU0'),
('Kaolin', 'XM7CN8'),
('Kaolin léger', 'XM2GB1'),
('Composé de lactobacillus acidophilus', 'XM1N12'),
('Lactobacillus acidophilus', 'XM0EB5'),
('Lactobacillus bifidus, lyophilisé', 'XM0QG1'),
('Lactobacillus bulgaricus', 'XM1TF2'),
('Lactobacillus sporogenes', 'XM4KH7'),
('Lignine, hémicellulose', 'XM48X2'),
('Lomotil', 'XM8683'),
('Bactérie miyairi', 'XM2UP7'),
('Pectine', 'XM2HR7'),
('Saccharomyces boulardii', 'XM4X08'),
('Huile danis', 'XM2663'),
('Antiflatulent', 'XM8A26'),
('Bétaïne', 'XM0090'),
('Sels biliaires', 'XM0TD5'),
('Carminatif', 'XM5TC9'),
('Cholagogues', 'XM5QD3'),
('Cholérétique', 'XM6RN6'),
('Cytochrome C', 'XM5CHO'),
('Acide déhydrocholique', 'XM0U08'),
('Foreur', 'XM0365'),
('Élastase', 'XM4RK4'),
('Enzyme de lintestin', 'XM5H83'),
('Florantryone', 'XM2Q01'),
('Enzymes gastriques', 'XM5BH7'),
('Gentiane', 'XM63F8'),
('Gingembre', 'XM1TN8'),
('Acide glutamique', 'XM0994'),
('Acide chlorhydrique à usage médical (aide à la digestion)', 'XM15D5'),
('Extrait de bile de Ox', 'XM2702'),
('Pancréatine', 'XM6HM1'),
('Pancrelipase', 'XM9Z07'),
('Papaïne', 'XM6DW4'),
('Papaïne, digestif', 'XM72V4'),
('Huile de menthe poivrée', 'XM1XP0'),
('Pepsine, digestif', 'XM17U7'),
('Phénylpropanol', 'XM7L34'),
('Tilactase', 'XM4U70'),
('Oxalate de cérium', 'XM4H25'),
('Cuivre, émétique', 'XM3ME7'),
('Sulfate de cuivre à usage médical, émétique', 'XM9FG8'),
('Moutarde noire', 'XM2WE8'),
('Chlorobutanol', 'XM5SW7'),
('Triméthobenzamide', 'XM8SN3'),
('Métopimazine', 'XM46N1'),
('Aprepitant', 'XM1DC1'),
('Casopitant', 'XM2633'),
('Rompitant', 'XM4IY6'),
('Pipamazine', 'XM2170'),
('Sulfonate dammonium, résine', 'XM3KJ5'),
('Lactobacillus', 'XM4KK2'),
('Carraghénine', 'XM4663'),
('Charbon végétal actif, antidote', 'XM8NN7'),
('Utilisation précisée de charbon autre dans le traitement de la diarrhée', 'XM4GA5'),
('Diméthylpolysiloxane', 'XM7ER1'),
('Médicament gastro-intestinal biologique', 'XM30A7'),
('Médicament gastro-intestinal précisé', 'XM0KJ8'),
('Glucuronolactone', 'XM7L13'),
('Stimulant hépatique', 'XM9Q94'),
('Agents biologiques de contrôle de la motilité intestinale', 'XM7EV4'),
('Résine anionique échangeuse dions', 'XM9S11'),
('Résine échangeuse dions (intestinal)', 'XM1AX0'),
('Extrait de réglisse', 'XM0UP4'),
('Mésalazine', 'XM8UW6'),
('Olsalazine', 'XM0TN5'),
('Stimulant de la sécrétion digestive pancréatique', 'XM73P5'),
('Polysilane', 'XM0EKO'),
('Alginate de sodium', 'XM2K96'),
('Amylosulfate de sodium', 'XM7M46'),
('Amylopectine sulfatée', 'XM7AL9'),
('Glycérol', 'XM5348'),
('Médicaments produisant du dioxyde de carbone', 'XM7DT2'),
('Lubiprostone', 'XM4U05'),
('Linaclotide', 'XM3086'),
('Prucalopride', 'XM2396'),
('Tégaserod', 'XM2SC1'),
('Plécanatide', 'XM78V7'),
('Essence', 'XM6DL1'),
('Éluxadoline', 'XM8136'),
('Hormone adrénocorticotrope', 'XM5Y80'),
('Hormone antéhypophysaire', 'XM7309'),
('Cosyntropine', 'XM1EM4'),
('Hormone folliculostimulante humaine', 'XM4MB2'),
('FSH', 'XM1027'),
('Bétahistine', 'XM14C0'),
('Cinnarizine', 'XM7CE7'),
('Flunarizine', 'XM52G4'),
('Acétylleucine', 'XM2U21'),
('Antihistaminiques', 'XM4J58'),
('Antiparkinsoniens', 'XM9G63'),
('Antiepileptiques', 'XM63D6'),
('Diamorphine', 'XM05B3'),
('Morphine, dérivés de la morphine et métabolites', 'XM69R4'),
('Opium', 'XM4ES0'),
('Oxycodone', 'XM4SL9'),
('Nalfurafine', 'XM9UH3'),
('Chlorure de sodium hypertonique (ophtalmique)', 'XM7SY2'),
('Édétate de sodium, préparation ophtalmique', 'XM2LQ4'),
('Ciclosporine en préparation ophtalmique', 'XM3ZG3'),
('Nandrolone en préparation ophtalmique', 'XM7UH0'),
('Apraclonidine', 'XM3XE4'),
('Vertéporfine', 'XM2Y24'),
('Acide spaglumique', 'XM63C9'),
('Bendazac', 'XM0P54'),
('Néomycine usage topique', 'XM7D13'),
('Inosine', 'XM8BH0'),
('Nitrofurazone', 'XM71W2'),
('Povidone iodée', 'XM24J7'),
('Résorcine, résorcinol médicinal', 'XM4549'),
('Dentifrice', 'XM3YZ7'),
('Pansement, chair vive', 'XM1JW3'),
('Huile deucalyptus', 'XM0PR1'),
('Huile de clous de girofles', 'XM3XP7'),
('Pâte dentaire de dévitalisation', 'XM8PE1'),
('Acide acétylsalicylique à usage topique', 'XM9023'),
('Olaflur', 'XM7K59'),
('Monofluorophosphate de sodium', 'XM5GY2'),
('Desoximétasone', 'XM3MB5'),
('Dexaméthasone topique', 'XM6TE1'),
('Diflorasone', 'XM8V58'),
('Diflucortolone', 'XM4XD6'),
('Acétonide de flucolrolone', 'XM4TV8'),
('Fludrocortisone topique', 'XM0WP2'),
('Fludroxycortide', 'XM84F4'),
('Fluméthasone', 'XM6LQ2'),
('Butyl de fluocortine', 'XM3EM1'),
('Fluorométholone', 'XM7MM0'),
('Fluprédnidène', 'XM52K8'),
('Flurandrénolide', 'XM5086'),
('Halcinonide', 'XM0ZX1'),
('Halométasone', 'XM8TL4'),
('Acéponate dhydrocortisone', 'XM8KB5'),
('Hydrocortisone topique', 'XM6JE7'),
('Prednicarbate', 'XM0ME0'),
('Prednisolone steaglate', 'XM1B59'),
('Prednisolone topique', 'XM09Z4'),
('Butyrate dhydrocortisone', 'XM4Y24'),
('Fluméthasone', 'XM5S53'),
('Fluperolone', 'XM41T8'),
('Butéprate', 'XM5ZS6'),
('Ulobétasol', 'XM64R0'),
('Difluprednate', 'XM6DT9'),
('Acéponate de méthylprednisolone', 'XM5EY3'),
('Acétonide de fluocinolone', 'XM4HA4'),
('Fluclorolone', 'XM1068'),
('Ciclétanide topique', 'XM3DFA');
COMMit;