START TRANSACTION;

CREATE DATABASE IF NOT EXISTS forza;
SET CHARACTER SET 'utf8';

USE forza;

CREATE TABLE `vaccins` (
  `code_vaccin` varchar(255) NOT NULL PRIMARY KEY,
  `designation` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO vaccins (`code_vaccin`, `designation`) VALUES
  ('VAC0909','Antitoxine Botulique'),
  ('VAC0867','Antitoxine Diphtérique, sans précision'),
  ('VAC0497','Immunoglobuline anti Tétanique, sans précision'),
  ('VAC0863','Immunoglobuline contre lhépatite B, sans précision'),
  ('VAC0862','Immunoglobuline contre la rougeole, sans précision'),
  ('VAC0941','Immunoglobuline contre le charbon, sans précision'),
  ('VAC0864','Immunoglobuline contre le virus de la varicelle, sans précision'),
  ('VAC0503','Immunoglobuline Rabique origine équine, sans précision'),
  ('VAC0502','Immunoglobuline Rabique, sans précision'),
  ('VAC0358','Immunoglobuline Rage origine humaine, sans précision'),
  ('VAC0894','Vaccin Adénovirus, sans précision'),
  ('VAC0919','Vaccin anti - Hib hbOC, sans précision'),
  ('VAC0918','Vaccin anti - Hib PRP - D, sans précision'),
  ('VAC0345','Vaccin anti - Hib PRP - T, sans précision'),
  ('VAC0134','Vaccin BCG, sans précision'),
  ('VAC0600','Vaccin bivalent OPV 1-3, sans précision'),
  ('VAC0937','Vaccin Botulisme, sans précision'),
  ('VAC0162','Vaccin Brucellose, sans précision'),
  ('VAC0804','Vaccin Charbon, sans précision'),
  ('VAC0144','Vaccin Choléra, sans précision'),
  ('VAC0807','Vaccin Choléra - Typhoïde inactivé, sans précision'),
  ('VAC0944','Vaccin Cholérique entier inactivé, voie orale, sans précision'),
  ('VAC0805','Vaccin Cholérique, entier inactivé, sans précision'),
  ('VAC0806','Vaccin Cholérique, vivant atténué, sans précision'),
  ('VAC0825','Vaccin combiné Hépatites A et B, sans précision'),
  ('VAC0907','Vaccin contre les Adénovirus de type 4, sans précision'),
  ('VAC0908','Vaccin contre les Adénovirus de type 7, sans précision'),
  ('VAC0163','Vaccin Coqueluche entier inactivé, sans précision'),
  ('VAC0795','Vaccin Coquelucheux acellulaire, sans précision'),
  ('VAC0796','Vaccin Coquelucheux, sans précision'),
  ('VAC1041','Vaccin Covid 19 à ARN, sans précision'),
  ('VAC0927','Vaccin Covid 19 à ARNm, dose pédiatrique, sans précision'),
  ('VAC1039','Vaccin Covid 19 à ARNm, virus originel, 50 microgrammes, sans précision'),
  ('VAC1043','Vaccin Covid 19 à sous unité protéique, sans précision'),
  ('VAC1042','Vaccin Covid 19 à vecteur viral non replicatif, sans précision'),
  ('VAC1044','Vaccin Covid 19 à virus entier inactivé, sans précision'),
  ('VAC0648','Vaccin Covid 19, sans précision'),
  ('VAC0155','Vaccin Dengue, sans précision'),
  ('VAC0382','Vaccin Diph - T Diphtérie - Tétanos, sans précision'),
  ('VAC0797','Vaccin Diph - T - Ca / ca, Diphtérie - Tétanos Coqueluche, sans précision'),
  ('VAC0855','Vaccin DiphTP - Diphtérie - Tétanos - Polio, sans précision'),
  ('VAC0138','Vaccin DiphTPCoq - Diphtérie - Tétanos Coqueluche - Polio, sans précision'),
  ('VAC0787','Vaccin DiphTRub - Diphtérie - Tétanos Rubéole, sans précision'),
  ('VAC0655','Vaccin Diphtérique, sans précision'),
  ('VAC0920','Vaccin dT - Diphtérie Tétanos, sans précision'),
  ('VAC0137','Vaccin DT, sans précision'),
  ('VAC0601','Vaccin DTC - Diphtérie Tétanos - Coqueluche, sans précision'),
  ('VAC0610','Vaccin dTca - Diphtérie Tétanos - Coqueluche, dose réduite, sans précision'),
  ('VAC0602','Vaccin DTCa - Diphtérie Tétanos - Coqueluche, dose standard, sans précision'),
  ('VAC0856','Vaccin DTCaHib - Diphtérie - Tétanos Coqueluche - Hib, sans précision'),
  ('VAC0585','Vaccin dTcaP - Diphtérie - Tétanos Coqueluche - Polio, dose réduite, sans précision'),
  ('VAC0551','Vaccin DTCaP - Diphtérie - Tétanos Coqueluche - Polio, sans précision'),
  ('VAC0136','Vaccin DTCe - Diphtérie Tétanos - Coqueluche, sans précision'),
  ('VAC0775','Vaccin DTCeHib - Diphtérie - Tétanos Coqueluche - Hib, sans précision'),
  ('VAC0857','Vaccin DTCoqHepB - Diphtérie - Tétanos Coqueluche - Hépatite B, sans précision'),
  ('VAC0800','Vaccin DTCoqHib - Diphtérie - Tétanos Coqueluche - Hib, sans précision'),
  ('VAC0790','Vaccin DTHepB - Diphtérie - Tétanos Hépatite B, sans précision'),
  ('VAC0799','Vaccin DTHib - Diphtérie - Tétanos - Hib, sans précision'),
  ('VAC0549','Vaccin dTP - Diphtérie Tétanos - Polio, dose réduite, sans précision'),
  ('VAC0088','Vaccin DTP - Diphtérie Tétanos - Polio, sans précision'),
  ('VAC0831','Vaccin Ebola, sans précision'),
  ('VAC0819','Vaccin Encéphalite Japonaise entier inactivé, sans précision'),
  ('VAC0146','Vaccin Encéphalite Japonaise vivant atténué 14-14-2, sans précision'),
  ('VAC0881','Vaccin Encéphalite Japonaise vivant atténué, sans précision'),
  ('VAC0921','Vaccin Encéphalite Japonaise, sans précision'),
  ('VAC0145','Vaccin Encéphalite à tiques, sans précision'),
  ('VAC1038','Vaccin Encéphalite à tiques, souche Neudörfl, dose adulte, sans précision'),
  ('VAC1037','Vaccin Encéphalite à tiques, souche Neudörfl, dose pédiatrique, sans précision'),
  ('VAC0895','Vaccin Encéphalite équine vénézuélienne, sans précision'),
  ('VAC0910','Vaccin entier inactivé contre hépatite A, dose adulte, sans précision'),
  ('VAC0111','Vaccin Fièvre jaune, sans précision'),
  ('VAC0896','Vaccin Fièvre Q, sans précision'),
  ('VAC0147','Vaccin Grippe A ( H1N1 ) 2009, sans précision'),
  ('VAC0820','Vaccin Grippe entier inactivé, sans précision'),
  ('VAC0929','Vaccin Grippe inactivé quadrivalent, dose pédiatrique, sans précision'),
  ('VAC0821','Vaccin Grippe inactivé, fractionné ou sous - unité, sans précision'),
  ('VAC0932','Vaccin Grippe quadrivalent recombinant, sans précision'),
  ('VAC0938','Vaccin Grippe quadrivalent, sans précision'),
  ('VAC0925','Vaccin Grippe trivalent inactivé, sans précision'),
  ('VAC0822','Vaccin Grippe vivant atténué, sans précision'),
  ('VAC0823','Vaccin Grippe VLP, sans précision'),
  ('VAC0110','Vaccin Grippe, sans précision'),
  ('VAC0143','Vaccin Haemophilus influenzae B, sans précision'),
  ('VAC0897','Vaccin Hantavirus, sans précision'),
  ('VAC0801','Vaccin HepB - Hib - Hépatite B - Hib, sans précision'),
  ('VAC0832','Vaccin Herpes Simplex, sans précision'),
  ('VAC0552','Vaccin hexavalent DTPCaHibHepB - Diphtérie - Tétanos - Polio Coqueluche - Hib Hépatite B, sans précision'),
  ('VAC0791','Vaccin hexavalent DTPCoqHepBHib - Diphtérie - Tétanos Coqueluche - Polio Hépatite B - Hib, sans précision'),
  ('VAC0344','Vaccin Hib PRP - OMP, sans précision'),
  ('VAC0808','Vaccin Hib - MenCY, sans précision'),
  ('VAC0798','Vaccin Hib - MeningoC, sans précision'),
  ('VAC0788','Vaccin Hib - Polio, sans précision'),
  ('VAC0858','Vaccin HPV bivalent, sans précision'),
  ('VAC0860','Vaccin HPV nonavalent, sans précision'),
  ('VAC0859','Vaccin HPV quadrivalent, sans précision'),
  ('VAC0156','Vaccin HPV, sans précision'),
  ('VAC0654','Vaccin Hépatite A + Hépatite B Adulte, sans précision'),
  ('VAC0653','Vaccin Hépatite A + Hépatite B Enfant, sans précision'),
  ('VAC0102','Vaccin Hépatite A inactivé, sans précision'),
  ('VAC0824','Vaccin Hépatite A virosomal, sans précision'),
  ('VAC0928','Vaccin Hépatite A vivant atténué, sans précision'),
  ('VAC0912','Vaccin Hépatite A, dose pédiatrique, sans précision'),
  ('VAC0911','Vaccin Hépatite A, monovalent, dose pédiatrique, sans précision'),
  ('VAC0916','Vaccin Hépatite B, monovalent pour les patients dialysés, sans précision'),
  ('VAC0915','Vaccin Hépatite B, monovalent, dose adulte, sans précision'),
  ('VAC0914','Vaccin Hépatite B, monovalent, dose pédiatrique, sans précision'),
  ('VAC0101','Vaccin Hépatite B, sans précision'),
  ('VAC0917','Vaccin Hépatite E, sans précision'),
  ('VAC0898','Vaccin Leishmaniose, sans précision'),
  ('VAC0148','Vaccin Leptospirose, sans précision'),
  ('VAC0853','Vaccin mOPV1 - Poliomyélitique oral monovalent type 1, sans précision'),
  ('VAC0852','Vaccin mOPV2 - Poliomyélitique oral monovalent type 2, sans précision'),
  ('VAC0854','Vaccin mOPV3 - Poliomyélitique oral monovalent type 3, sans précision'),
  ('VAC0861','Vaccin Méningococcique B multicomposé, sans précision'),
  ('VAC0810','Vaccin Méningocoque polyosidique polyvalent, sans précision'),
  ('VAC0866','Vaccin Méningocoque A conjugué, sans précision'),
  ('VAC0865','Vaccin Méningocoque A non conjugué, sans précision'),
  ('VAC0811','Vaccin Méningocoque B, sans précision'),
  ('VAC0149','Vaccin Méningocoque B : 14 : P1.7,16, sans précision'),
  ('VAC0150','Vaccin Méningocoque C conjugué, sans précision'),
  ('VAC0809','Vaccin Méningocoque polyosidique monovalent, sans précision'),
  ('VAC0945','Vaccin Méningocoque sérogroupe inconnu, sans précision'),
  ('VAC0151','Vaccin Méningocoques A + C, sans précision'),
  ('VAC0643','Vaccin Méningocoques ACWY conjugué, sans précision'),
  ('VAC0152','Vaccin Méningocoques ACWY non conjugué, sans précision'),
  ('VAC0153','Vaccin Oreillons, sans précision'),
  ('VAC0154','Vaccin Paludisme, sans précision'),
  ('VAC0596','Vaccin pentavalent DTCaHibHepB - Diphtérie - Tétanos Coqueluche - Hib Hépatite B, sans précision'),
  ('VAC0506','Vaccin pentavalent DTCaHibP - Diphtérie Tétanos - Coqueluche Hib - Polio, sans précision'),
  ('VAC0598','Vaccin pentavalent DTCeHibHepB - Diphtérie - Tétanos Coqueluche - Hib Hépatite B, sans précision'),
  ('VAC0553','Vaccin pentavalent DTCeHibP - Diphtérie Tétanos - Coqueluche Hib - Polio, sans précision'),
  ('VAC0599','Vaccin pentavalent DTCoqHibHepB - Diphtérie - Tétanos Coqueluche - Hib Hépatite B, sans précision'),
  ('VAC0880','Vaccin pentavalent DTCoqHibP - Diphtérie Tétanos - Coqueluche Hib - Polio, sans précision'),
  ('VAC0792','Vaccin pentavalent DTCoqPHepB - Diphtérie - Tétanos Coqueluche - Polio Hépatite B, sans précision'),
  ('VAC0812','Vaccin Peste entier inactivé, sans précision'),
  ('VAC0815','Vaccin Pneumo - Hib, sans précision'),
  ('VAC0997','Vaccin Pneumocoque conjugué 13 - valent, sans précision'),
  ('VAC0324','Vaccin Pneumocoque conjugué 7 - valent, sans précision'),
  ('VAC0814','Vaccin Pneumocoque conjugué, sans précision'),
  ('VAC0339','Vaccin Pneumocoque non conjugué 23 - valent, sans précision'),
  ('VAC0813','Vaccin Pneumocoque non conjugué, sans précision'),
  ('VAC0157','Vaccin Pneumocoque, sans précision'),
  ('VAC0270','Vaccin Polio inactivé, sans précision'),
  ('VAC0802','Vaccin Polio oral monovalent - type non connu, sans précision'),
  ('VAC0320','Vaccin Polio oral trivalent, sans précision'),
  ('VAC0135','Vaccin Polio, sans précision'),
  ('VAC0084','Vaccin prépandémique H5N1 contre la grippe, sans précision'),
  ('VAC0943','Vaccin Rage cellules diploïdes, sans précision'),
  ('VAC0942','Vaccin Rage embryon de poulet, sans précision'),
  ('VAC0905','Vaccin Rage PHKCV, sans précision'),
  ('VAC0904','Vaccin Rage préparé sur embryon de canard, sans précision'),
  ('VAC0903','Vaccin Rage type Fuenzalida, sans précision'),
  ('VAC0902','Vaccin Rage type Semple, sans précision'),
  ('VAC0131','Vaccin Rage, sans précision'),
  ('VAC0623','Vaccin RO - Rougeole Oreillons, sans précision'),
  ('VAC0130','Vaccin ROR ( ou RRO ), sans précision'),
  ('VAC0827','Vaccin ROR - V Rougeole - Oreillons Rubéole - Varicelle, sans précision'),
  ('VAC0828','Vaccin Rotavirus pentavalent, sans précision'),
  ('VAC0158','Vaccin Rotavirus, sans précision'),
  ('VAC0114','Vaccin Rougeoleux, monovalent, sans précision'),
  ('VAC0550','Vaccin RR - Rougeole Rubéole, sans précision'),
  ('VAC0113','Vaccin Rubéole, sans précision'),
  ('VAC0829','Vaccin Rubéole Oreillons, sans précision'),
  ('VAC0794','Vaccin T - igT - Tétanos, sans précision'),
  ('VAC0380','Vaccin TP - Tétanos polio, sans précision'),
  ('VAC0849','Vaccin Tularémie, sans précision'),
  ('VAC0712','Vaccin Typh - HepA - Typhoïde - Hépatite A, sans précision'),
  ('VAC0818','Vaccin Typho Paratyphoïdique, sans précision'),
  ('VAC0711','Vaccin Typhoïde conjugué, sans précision'),
  ('VAC0817','Vaccin Typhoïde entier inactivé, sans précision'),
  ('VAC0424','Vaccin Typhoïde oral vivant atténué, sans précision'),
  ('VAC0713','Vaccin Typhoïde polyosidique, sans précision'),
  ('VAC0112','Vaccin Typhoïde, sans précision'),
  ('VAC0512','Vaccin Typhus, sans précision'),
  ('VAC0132','Vaccin Tétanique, sans précision'),
  ('VAC0159','Vaccin Varicelle, sans précision'),
  ('VAC0133','Vaccin Variole, sans précision'),
  ('VAC0899','Vaccin Virus Parainfluenza humains, sans précision'),
  ('VAC0923','Vaccin Virus Respiratoire Syncytial, sans précision'),
  ('VAC0922','Vaccin vivant atténué contre les Adénovirus, type 4 et type 7, voie orale, sans précision'),
  ('VAC0830','Vaccin Zona sous unitaire, sans précision'),
  ('VAC0160','Vaccin Zona vivant atténué, sans précision'),
  ('VAC0906','Vaccin Zona, sans précision');

COMMIT;