apiVersion: v1
kind: Service
metadata:
  labels:
    app: personnel-db
  name: personnel-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: personnel-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: personnel-db
  name: personnel-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personnel-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: personnel-db
    spec:
      containers:
        - image: medicalife/personnel-db:latest
          name: personnel-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/personnel
              name: personnel-data
      restartPolicy: Always
      volumes:
        - name: personnel-data
          persistentVolumeClaim:
            claimName: personnel-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: personnel-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
