version: '3'
networks:
  static-network:
    ipam:
      driver: default
      config:
          - subnet: 10.10.10.0/24
            gateway: 10.10.10.1
volumes:
  mysql-data:
services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    networks:
      static-network:
        ipv4_address: 10.10.10.254
    ports:
    - "443:443"
    - "80:80"
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      static-network:
        ipv4_address: 10.10.10.30
    ports:
     - "8080:8080"
  database:
    build: ./database
    container_name: database
    networks:
      static-network:
        ipv4_address: 10.10.10.50
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  auth_service:
    build: ./auth
    container_name: auth_service
    networks:
      static-network:
        ipv4_address: 10.10.10.10
    ports:
     - "8081:8081"
  backend:
    build: ./backend
    container_name: backend
    networks:
      static-network:
        ipv4_address: 10.10.10.20
    ports:
     - "8082:8082"