version: '3'
services:
  database:
    build: ./database
    container_name: database
    ports:
      - "3307:3306"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
     - "80:80"
     - "443:443"
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
     - "8080:8080"
  auth_service:
    build: ./auth
    container_name: auth_service
    ports:
     - "8081:8081"