-- --------------------------------------------------------

--
-- Structure de la table `vaccines`
--

CREATE TABLE `vaccines` (
  `Codes` varchar(255) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `nom_complet` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `vaccines`
--

INSERT INTO `vaccines` (`Codes`, `Name`, `nom_complet`) VALUES
('VAC0909', 'Antitoxine Botulique', 'VAC0909 - Antitoxine Botulique'),
('VAC0867', 'Antitoxine Diphtérique ,\nsans précision', 'VAC0867 - Antitoxine Diphtérique ,\nsans précision'),
('VAC0497', 'Immunoglobuline anti\nTétanique , sans\nprécision', 'VAC0497 - Immunoglobuline anti\nTétanique , sans\nprécision'),
('VAC0863', 'Immunoglobuline contre\nlhépatite B , sans\nprécision', 'VAC0863 - Immunoglobuline contre\nlhépatite B , sans\nprécision'),
('VAC0862', 'Immunoglobuline contre\nla rougeole , sans\nprécision', 'VAC0862 - Immunoglobuline contre\nla rougeole , sans\nprécision'),
('VAC0941', 'Immunoglobuline contre\nle charbon , sans\nprécision', 'VAC0941 - Immunoglobuline contre\nle charbon , sans\nprécision'),
('VAC0864', 'Immunoglobuline contre\nle virus de la varicelle ,\nsans précision', 'VAC0864 - Immunoglobuline contre\nle virus de la varicelle ,\nsans précision'),
('VAC0503', 'Immunoglobuline\nRabique origine équine ,\nsans précision', 'VAC0503 - Immunoglobuline\nRabique origine équine ,\nsans précision'),
('VAC0502', 'Immunoglobuline\nRabique , sans précision', 'VAC0502 - Immunoglobuline\nRabique , sans précision'),
('VAC0358', 'Immunoglobuline Rage\norigine humaine , sans\nprécision', 'VAC0358 - Immunoglobuline Rage\norigine humaine , sans\nprécision'),
('VAC0894', 'Vaccin Adénovirus , sans\nprécision', 'VAC0894 - Vaccin Adénovirus , sans\nprécision'),
('VAC0919', 'Vaccin anti - Hib hbOC ,\nsans précision', 'VAC0919 - Vaccin anti - Hib hbOC ,\nsans précision'),
('VAC0918', 'Vaccin anti - Hib PRP - D ,\nsans précision', 'VAC0918 - Vaccin anti - Hib PRP - D ,\nsans précision'),
('VAC0345', 'Vaccin anti - Hib PRP - T ,\nsans précision', 'VAC0345 - Vaccin anti - Hib PRP - T ,\nsans précision'),
('VAC0134', 'Vaccin BCG , sans\nprécision', 'VAC0134 - Vaccin BCG , sans\nprécision'),
('VAC0600', 'Vaccin bivalent OPV 1-3 ,\nsans précision', 'VAC0600 - Vaccin bivalent OPV 1-3 ,\nsans précision'),
('VAC0937', 'Vaccin Botulisme , sans\nprécision', 'VAC0937 - Vaccin Botulisme , sans\nprécision'),
('VAC0162', 'Vaccin Brucellose , sans\nprécision', 'VAC0162 - Vaccin Brucellose , sans\nprécision'),
('VAC0804', 'Vaccin Charbon , sans\nprécision', 'VAC0804 - Vaccin Charbon , sans\nprécision'),
('VAC0144', 'Vaccin Choléra , sans\nprécision', 'VAC0144 - Vaccin Choléra , sans\nprécision'),
('VAC0807', 'Vaccin Choléra - Typhoïde\ninactivé , sans précision', 'VAC0807 - Vaccin Choléra - Typhoïde\ninactivé , sans précision'),
('VAC0944', 'Vaccin Cholérique entier\ninactivé , voie orale , sans\nprécision', 'VAC0944 - Vaccin Cholérique entier\ninactivé , voie orale , sans\nprécision'),
('VAC0805', 'Vaccin Cholérique ,\nentier inactivé , sans\nprécision', 'VAC0805 - Vaccin Cholérique ,\nentier inactivé , sans\nprécision'),
('VAC0806', 'Vaccin Cholérique ,\nvivant atténué , sans\nprécision', 'VAC0806 - Vaccin Cholérique ,\nvivant atténué , sans\nprécision'),
('VAC0825', 'Vaccin combiné\nHépatites A et B , sans\nprécision', 'VAC0825 - Vaccin combiné\nHépatites A et B , sans\nprécision'),
('VAC0907', 'Vaccin contre les\nAdénovirus de type 4 ,\nsans précision', 'VAC0907 - Vaccin contre les\nAdénovirus de type 4 ,\nsans précision'),
('VAC0908', 'Vaccin contre les\nAdénovirus de type 7 ,\nsans précision', 'VAC0908 - Vaccin contre les\nAdénovirus de type 7 ,\nsans précision'),
('VAC0163', 'Vaccin Coqueluche\nentier inactivé , sans\nprécision', 'VAC0163 - Vaccin Coqueluche\nentier inactivé , sans\nprécision'),
('VAC0795', 'Vaccin Coquelucheux\nacellulaire , sans\nprécision', 'VAC0795 - Vaccin Coquelucheux\nacellulaire , sans\nprécision'),
('VAC0796', 'Vaccin Coquelucheux ,\nsans précision', 'VAC0796 - Vaccin Coquelucheux ,\nsans précision'),
('VAC1041', 'Vaccin Covid 19 à ARN ,\nsans précision', 'VAC1041 - Vaccin Covid 19 à ARN ,\nsans précision'),
('VAC0927', 'Vaccin Covid 19 à\nARNm , dose pédiatrique ,\nsans précision', 'VAC0927 - Vaccin Covid 19 à\nARNm , dose pédiatrique ,\nsans précision'),
('VAC1039', 'Vaccin Covid 19 à\nARNm , virus originel , 50\nmicrogrammes , sans\nprécision', 'VAC1039 - Vaccin Covid 19 à\nARNm , virus originel , 50\nmicrogrammes , sans\nprécision'),
('VAC1043', 'Vaccin Covid 19 à sous\nunité protéique , sans\nprécision', 'VAC1043 - Vaccin Covid 19 à sous\nunité protéique , sans\nprécision'),
('VAC1042', 'Vaccin Covid 19 à\nvecteur viral non\nreplicatif , sans précision', 'VAC1042 - Vaccin Covid 19 à\nvecteur viral non\nreplicatif , sans précision'),
('VAC1044', 'Vaccin Covid 19 à virus\nentier inactivé , sans\nprécision', 'VAC1044 - Vaccin Covid 19 à virus\nentier inactivé , sans\nprécision'),
('VAC0648', 'Vaccin Covid 19 , sans\nprécision', 'VAC0648 - Vaccin Covid 19 , sans\nprécision'),
('VAC0155', 'Vaccin Dengue , sans\nprécision', 'VAC0155 - Vaccin Dengue , sans\nprécision'),
('VAC0382', 'Vaccin Diph - T\nDiphtérie - Tétanos , sans\nprécision', 'VAC0382 - Vaccin Diph - T\nDiphtérie - Tétanos , sans\nprécision'),
('VAC0797', 'Vaccin Diph - T - Ca / ca ,\nDiphtérie - Tétanos\nCoqueluche , sans\nprécision', 'VAC0797 - Vaccin Diph - T - Ca / ca ,\nDiphtérie - Tétanos\nCoqueluche , sans\nprécision'),
('VAC0855', 'Vaccin DiphTP -\nDiphtérie - Tétanos - Polio ,\nsans précision', 'VAC0855 - Vaccin DiphTP -\nDiphtérie - Tétanos - Polio ,\nsans précision'),
('VAC0138', 'Vaccin DiphTPCoq -\nDiphtérie - Tétanos\nCoqueluche - Polio , sans\nprécision', 'VAC0138 - Vaccin DiphTPCoq -\nDiphtérie - Tétanos\nCoqueluche - Polio , sans\nprécision'),
('VAC0787', 'Vaccin DiphTRub -\nDiphtérie - Tétanos\nRubéole , sans précision', 'VAC0787 - Vaccin DiphTRub -\nDiphtérie - Tétanos\nRubéole , sans précision'),
('VAC0655', 'Vaccin Diphtérique , sans\nprécision', 'VAC0655 - Vaccin Diphtérique , sans\nprécision'),
('VAC0920', 'Vaccin dT - Diphtérie\nTétanos , sans précision', 'VAC0920 - Vaccin dT - Diphtérie\nTétanos , sans précision'),
('VAC0137', 'Vaccin DT , sans\nprécision', 'VAC0137 - Vaccin DT , sans\nprécision'),
('VAC0601', 'Vaccin DTC - Diphtérie\nTétanos - Coqueluche ,\nsans précision', 'VAC0601 - Vaccin DTC - Diphtérie\nTétanos - Coqueluche ,\nsans précision'),
('VAC0610', 'Vaccin dTca - Diphtérie\nTétanos - Coqueluche ,\ndose réduite , sans\nprécision', 'VAC0610 - Vaccin dTca - Diphtérie\nTétanos - Coqueluche ,\ndose réduite , sans\nprécision'),
('VAC0602', 'Vaccin DTCa - Diphtérie\nTétanos - Coqueluche ,\ndose standard , sans\nprécision', 'VAC0602 - Vaccin DTCa - Diphtérie\nTétanos - Coqueluche ,\ndose standard , sans\nprécision'),
('VAC0856', 'Vaccin DTCaHib -\nDiphtérie - Tétanos\nCoqueluche - Hib , sans\nprécision', 'VAC0856 - Vaccin DTCaHib -\nDiphtérie - Tétanos\nCoqueluche - Hib , sans\nprécision'),
('VAC0585', 'Vaccin dTcaP -\nDiphtérie - Tétanos\nCoqueluche - Polio , dose\nréduite , sans précision', 'VAC0585 - Vaccin dTcaP -\nDiphtérie - Tétanos\nCoqueluche - Polio , dose\nréduite , sans précision'),
('VAC0551', 'Vaccin DTCaP -\nDiphtérie - Tétanos\nCoqueluche - Polio , sans\nprécision', 'VAC0551 - Vaccin DTCaP -\nDiphtérie - Tétanos\nCoqueluche - Polio , sans\nprécision'),
('VAC0136', 'Vaccin DTCe - Diphtérie\nTétanos - Coqueluche ,\nsans précision', 'VAC0136 - Vaccin DTCe - Diphtérie\nTétanos - Coqueluche ,\nsans précision'),
('VAC0775', 'Vaccin DTCeHib -\nDiphtérie - Tétanos\nCoqueluche - Hib , sans\nprécision', 'VAC0775 - Vaccin DTCeHib -\nDiphtérie - Tétanos\nCoqueluche - Hib , sans\nprécision'),
('VAC0857', 'Vaccin DTCoqHepB -\nDiphtérie - Tétanos\nCoqueluche - Hépatite B ,\nsans précision', 'VAC0857 - Vaccin DTCoqHepB -\nDiphtérie - Tétanos\nCoqueluche - Hépatite B ,\nsans précision'),
('VAC0800', 'Vaccin DTCoqHib -\nDiphtérie - Tétanos\nCoqueluche - Hib , sans\nprécision', 'VAC0800 - Vaccin DTCoqHib -\nDiphtérie - Tétanos\nCoqueluche - Hib , sans\nprécision'),
('VAC0790', 'Vaccin DTHepB -\nDiphtérie - Tétanos\nHépatite B , sans\nprécision', 'VAC0790 - Vaccin DTHepB -\nDiphtérie - Tétanos\nHépatite B , sans\nprécision'),
('VAC0799', 'Vaccin DTHib -\nDiphtérie - Tétanos - Hib ,\nsans précision', 'VAC0799 - Vaccin DTHib -\nDiphtérie - Tétanos - Hib ,\nsans précision'),
('VAC0549', 'Vaccin dTP - Diphtérie\nTétanos - Polio , dose\nréduite , sans précision', 'VAC0549 - Vaccin dTP - Diphtérie\nTétanos - Polio , dose\nréduite , sans précision'),
('VAC0088', 'Vaccin DTP - Diphtérie\nTétanos - Polio , sans\nprécision', 'VAC0088 - Vaccin DTP - Diphtérie\nTétanos - Polio , sans\nprécision'),
('VAC0831', 'Vaccin Ebola , sans\nprécision', 'VAC0831 - Vaccin Ebola , sans\nprécision'),
('VAC0819', 'Vaccin Encéphalite\nJaponaise entier\ninactivé , sans précision', 'VAC0819 - Vaccin Encéphalite\nJaponaise entier\ninactivé , sans précision'),
('VAC0146', 'Vaccin Encéphalite\nJaponaise vivant\natténué 14-14-2 , sans\nprécision', 'VAC0146 - Vaccin Encéphalite\nJaponaise vivant\natténué 14-14-2 , sans\nprécision'),
('VAC0881', 'Vaccin Encéphalite\nJaponaise vivant\natténué , sans précision', 'VAC0881 - Vaccin Encéphalite\nJaponaise vivant\natténué , sans précision'),
('VAC0921', 'Vaccin Encéphalite\nJaponaise , sans\nprécision', 'VAC0921 - Vaccin Encéphalite\nJaponaise , sans\nprécision'),
('VAC0145', 'Vaccin Encéphalite à\ntiques , sans précision', 'VAC0145 - Vaccin Encéphalite à\ntiques , sans précision'),
('VAC1038', 'Vaccin Encéphalite à\ntiques , souche Neudörfl ,\ndose adulte , sans\nprécision', 'VAC1038 - Vaccin Encéphalite à\ntiques , souche Neudörfl ,\ndose adulte , sans\nprécision'),
('VAC1037', 'Vaccin Encéphalite à\ntiques , souche Neudörfl ,\ndose pédiatrique , sans\nprécision', 'VAC1037 - Vaccin Encéphalite à\ntiques , souche Neudörfl ,\ndose pédiatrique , sans\nprécision'),
('VAC0895', 'Vaccin Encéphalite\néquine vénézuélienne ,\nsans précision', 'VAC0895 - Vaccin Encéphalite\néquine vénézuélienne ,\nsans précision'),
('VAC0910', 'Vaccin entier inactivé\ncontre hépatite A , dose\nadulte , sans précision', 'VAC0910 - Vaccin entier inactivé\ncontre hépatite A , dose\nadulte , sans précision'),
('VAC0111', 'Vaccin Fièvre jaune ,\nsans précision', 'VAC0111 - Vaccin Fièvre jaune ,\nsans précision'),
('VAC0896', 'Vaccin Fièvre Q , sans\nprécision', 'VAC0896 - Vaccin Fièvre Q , sans\nprécision'),
('VAC0147', 'Vaccin Grippe\nA ( H1N1 ) 2009 , sans\nprécision', 'VAC0147 - Vaccin Grippe\nA ( H1N1 ) 2009 , sans\nprécision'),
('VAC0820', 'Vaccin Grippe entier\ninactivé , sans précision', 'VAC0820 - Vaccin Grippe entier\ninactivé , sans précision'),
('VAC0929', 'Vaccin Grippe inactivé\nquadrivalent , dose\npédiatrique , sans\nprécision', 'VAC0929 - Vaccin Grippe inactivé\nquadrivalent , dose\npédiatrique , sans\nprécision'),
('VAC0821', 'Vaccin Grippe inactivé ,\nfractionné ou sous - unité ,\nsans précision', 'VAC0821 - Vaccin Grippe inactivé ,\nfractionné ou sous - unité ,\nsans précision'),
('VAC0932', 'Vaccin Grippe\nquadrivalent\nrecombinant , sans\nprécision', 'VAC0932 - Vaccin Grippe\nquadrivalent\nrecombinant , sans\nprécision'),
('VAC0938', 'Vaccin Grippe\nquadrivalent , sans\nprécision', 'VAC0938 - Vaccin Grippe\nquadrivalent , sans\nprécision'),
('VAC0925', 'Vaccin Grippe trivalent\ninactivé , sans précision', 'VAC0925 - Vaccin Grippe trivalent\ninactivé , sans précision'),
('VAC0822', 'Vaccin Grippe vivant\natténué , sans précision', 'VAC0822 - Vaccin Grippe vivant\natténué , sans précision'),
('VAC0823', 'Vaccin Grippe VLP , sans\nprécision', 'VAC0823 - Vaccin Grippe VLP , sans\nprécision'),
('VAC0110', 'Vaccin Grippe , sans\nprécision', 'VAC0110 - Vaccin Grippe , sans\nprécision'),
('VAC0143', 'Vaccin Haemophilus\ninfluenzae B , sans\nprécision', 'VAC0143 - Vaccin Haemophilus\ninfluenzae B , sans\nprécision'),
('VAC0897', 'Vaccin Hantavirus , sans\nprécision', 'VAC0897 - Vaccin Hantavirus , sans\nprécision'),
('VAC0801', 'Vaccin HepB - Hib -\nHépatite B - Hib , sans\nprécision', 'VAC0801 - Vaccin HepB - Hib -\nHépatite B - Hib , sans\nprécision'),
('VAC0832', 'Vaccin Herpes Simplex ,\nsans précision', 'VAC0832 - Vaccin Herpes Simplex ,\nsans précision'),
('VAC0552', 'Vaccin hexavalent\nDTPCaHibHepB -\nDiphtérie - Tétanos - Polio\nCoqueluche - Hib\nHépatite B , sans\nprécision', 'VAC0552 - Vaccin hexavalent\nDTPCaHibHepB -\nDiphtérie - Tétanos - Polio\nCoqueluche - Hib\nHépatite B , sans\nprécision'),
('VAC0791', 'Vaccin hexavalent\nDTPCoqHepBHib -\nDiphtérie - Tétanos\nCoqueluche - Polio\nHépatite B - Hib , sans\nprécision', 'VAC0791 - Vaccin hexavalent\nDTPCoqHepBHib -\nDiphtérie - Tétanos\nCoqueluche - Polio\nHépatite B - Hib , sans\nprécision'),
('VAC0344', 'Vaccin Hib PRP - OMP ,\nsans précision', 'VAC0344 - Vaccin Hib PRP - OMP ,\nsans précision'),
('VAC0808', 'Vaccin Hib - MenCY , sans\nprécision', 'VAC0808 - Vaccin Hib - MenCY , sans\nprécision'),
('VAC0798', 'Vaccin Hib - MeningoC ,\nsans précision', 'VAC0798 - Vaccin Hib - MeningoC ,\nsans précision'),
('VAC0788', 'Vaccin Hib - Polio , sans\nprécision', 'VAC0788 - Vaccin Hib - Polio , sans\nprécision'),
('VAC0858', 'Vaccin HPV bivalent ,\nsans précision', 'VAC0858 - Vaccin HPV bivalent ,\nsans précision'),
('VAC0860', 'Vaccin HPV nonavalent ,\nsans précision', 'VAC0860 - Vaccin HPV nonavalent ,\nsans précision'),
('VAC0859', 'Vaccin HPV\nquadrivalent , sans\nprécision', 'VAC0859 - Vaccin HPV\nquadrivalent , sans\nprécision'),
('VAC0156', 'Vaccin HPV , sans\nprécision', 'VAC0156 - Vaccin HPV , sans\nprécision'),
('VAC0654', 'Vaccin Hépatite A +\nHépatite B Adulte , sans\nprécision', 'VAC0654 - Vaccin Hépatite A +\nHépatite B Adulte , sans\nprécision'),
('VAC0653', 'Vaccin Hépatite A +\nHépatite B Enfant , sans\nprécision', 'VAC0653 - Vaccin Hépatite A +\nHépatite B Enfant , sans\nprécision'),
('VAC0102', 'Vaccin Hépatite A\ninactivé , sans précision', 'VAC0102 - Vaccin Hépatite A\ninactivé , sans précision'),
('VAC0824', 'Vaccin Hépatite A\nvirosomal , sans\nprécision', 'VAC0824 - Vaccin Hépatite A\nvirosomal , sans\nprécision'),
('VAC0928', 'Vaccin Hépatite A vivant\natténué , sans précision', 'VAC0928 - Vaccin Hépatite A vivant\natténué , sans précision'),
('VAC0912', 'Vaccin Hépatite A , dose\npédiatrique , sans\nprécision', 'VAC0912 - Vaccin Hépatite A , dose\npédiatrique , sans\nprécision'),
('VAC0911', 'Vaccin Hépatite A ,\nmonovalent , dose\npédiatrique , sans\nprécision', 'VAC0911 - Vaccin Hépatite A ,\nmonovalent , dose\npédiatrique , sans\nprécision'),
('VAC0916', 'Vaccin Hépatite B ,\nmonovalent pour les\npatients dialysés , sans\nprécision', 'VAC0916 - Vaccin Hépatite B ,\nmonovalent pour les\npatients dialysés , sans\nprécision'),
('VAC0915', 'Vaccin Hépatite B ,\nmonovalent , dose\nadulte , sans précision', 'VAC0915 - Vaccin Hépatite B ,\nmonovalent , dose\nadulte , sans précision'),
('VAC0914', 'Vaccin Hépatite B ,\nmonovalent , dose\npédiatrique , sans\nprécision', 'VAC0914 - Vaccin Hépatite B ,\nmonovalent , dose\npédiatrique , sans\nprécision'),
('VAC0101', 'Vaccin Hépatite B , sans\nprécision', 'VAC0101 - Vaccin Hépatite B , sans\nprécision'),
('VAC0917', 'Vaccin Hépatite E , sans\nprécision', 'VAC0917 - Vaccin Hépatite E , sans\nprécision'),
('VAC0898', 'Vaccin Leishmaniose ,\nsans précision', 'VAC0898 - Vaccin Leishmaniose ,\nsans précision'),
('VAC0148', 'Vaccin Leptospirose ,\nsans précision', 'VAC0148 - Vaccin Leptospirose ,\nsans précision'),
('VAC0853', 'Vaccin mOPV1 -\nPoliomyélitique oral\nmonovalent type 1 , sans\nprécision', 'VAC0853 - Vaccin mOPV1 -\nPoliomyélitique oral\nmonovalent type 1 , sans\nprécision'),
('VAC0852', 'Vaccin mOPV2 -\nPoliomyélitique oral\nmonovalent type 2 , sans\nprécision', 'VAC0852 - Vaccin mOPV2 -\nPoliomyélitique oral\nmonovalent type 2 , sans\nprécision'),
('VAC0854', 'Vaccin mOPV3 -\nPoliomyélitique oral\nmonovalent type 3 , sans\nprécision', 'VAC0854 - Vaccin mOPV3 -\nPoliomyélitique oral\nmonovalent type 3 , sans\nprécision'),
('VAC0861', 'Vaccin\nMéningococcique B\nmulticomposé , sans\nprécision', 'VAC0861 - Vaccin\nMéningococcique B\nmulticomposé , sans\nprécision'),
('VAC0810', 'Vaccin Méningocoque\npolyosidique polyvalent ,\nsans précision', 'VAC0810 - Vaccin Méningocoque\npolyosidique polyvalent ,\nsans précision'),
('VAC0866', 'Vaccin Méningocoque A\nconjugué , sans précision', 'VAC0866 - Vaccin Méningocoque A\nconjugué , sans précision'),
('VAC0865', 'Vaccin Méningocoque A\nnon conjugué , sans\nprécision', 'VAC0865 - Vaccin Méningocoque A\nnon conjugué , sans\nprécision'),
('VAC0811', 'Vaccin Méningocoque B ,\nsans précision', 'VAC0811 - Vaccin Méningocoque B ,\nsans précision'),
('VAC0149', 'Vaccin Méningocoque\nB : 14 : P1.7,16 , sans\nprécision', 'VAC0149 - Vaccin Méningocoque\nB : 14 : P1.7,16 , sans\nprécision'),
('VAC0150', 'Vaccin Méningocoque C\nconjugué , sans précision', 'VAC0150 - Vaccin Méningocoque C\nconjugué , sans précision'),
('VAC0809', 'Vaccin Méningocoque\npolyosidique\nmonovalent , sans\nprécision', 'VAC0809 - Vaccin Méningocoque\npolyosidique\nmonovalent , sans\nprécision'),
('VAC0945', 'Vaccin Méningocoque\nsérogroupe inconnu ,\nsans précision', 'VAC0945 - Vaccin Méningocoque\nsérogroupe inconnu ,\nsans précision'),
('VAC0151', 'Vaccin Méningocoques\nA + C , sans précision', 'VAC0151 - Vaccin Méningocoques\nA + C , sans précision'),
('VAC0643', 'Vaccin Méningocoques\nACWY conjugué , sans\nprécision', 'VAC0643 - Vaccin Méningocoques\nACWY conjugué , sans\nprécision'),
('VAC0152', 'Vaccin Méningocoques\nACWY non conjugué ,\nsans précision', 'VAC0152 - Vaccin Méningocoques\nACWY non conjugué ,\nsans précision'),
('VAC0153', 'Vaccin Oreillons , sans\nprécision', 'VAC0153 - Vaccin Oreillons , sans\nprécision'),
('VAC0154', 'Vaccin Paludisme , sans\nprécision', 'VAC0154 - Vaccin Paludisme , sans\nprécision'),
('VAC0596', 'Vaccin pentavalent\nDTCaHibHepB -\nDiphtérie - Tétanos\nCoqueluche - Hib\nHépatite B , sans\nprécision', 'VAC0596 - Vaccin pentavalent\nDTCaHibHepB -\nDiphtérie - Tétanos\nCoqueluche - Hib\nHépatite B , sans\nprécision'),
('VAC0506', 'Vaccin pentavalent\nDTCaHibP - Diphtérie\nTétanos - Coqueluche\nHib - Polio , sans précision', 'VAC0506 - Vaccin pentavalent\nDTCaHibP - Diphtérie\nTétanos - Coqueluche\nHib - Polio , sans précision'),
('VAC0598', 'Vaccin pentavalent\nDTCeHibHepB -\nDiphtérie - Tétanos\nCoqueluche - Hib\nHépatite B , sans\nprécision', 'VAC0598 - Vaccin pentavalent\nDTCeHibHepB -\nDiphtérie - Tétanos\nCoqueluche - Hib\nHépatite B , sans\nprécision'),
('VAC0553', 'Vaccin pentavalent\nDTCeHibP - Diphtérie\nTétanos - Coqueluche\nHib - Polio , sans précision', 'VAC0553 - Vaccin pentavalent\nDTCeHibP - Diphtérie\nTétanos - Coqueluche\nHib - Polio , sans précision'),
('VAC0599', 'Vaccin pentavalent\nDTCoqHibHepB -\nDiphtérie - Tétanos\nCoqueluche - Hib\nHépatite B , sans\nprécision', 'VAC0599 - Vaccin pentavalent\nDTCoqHibHepB -\nDiphtérie - Tétanos\nCoqueluche - Hib\nHépatite B , sans\nprécision'),
('VAC0880', 'Vaccin pentavalent\nDTCoqHibP - Diphtérie\nTétanos - Coqueluche\nHib - Polio , sans précision', 'VAC0880 - Vaccin pentavalent\nDTCoqHibP - Diphtérie\nTétanos - Coqueluche\nHib - Polio , sans précision'),
('VAC0792', 'Vaccin pentavalent\nDTCoqPHepB -\nDiphtérie - Tétanos\nCoqueluche - Polio\nHépatite B , sans\nprécision', 'VAC0792 - Vaccin pentavalent\nDTCoqPHepB -\nDiphtérie - Tétanos\nCoqueluche - Polio\nHépatite B , sans\nprécision'),
('VAC0812', 'Vaccin Peste entier\ninactivé , sans précision', 'VAC0812 - Vaccin Peste entier\ninactivé , sans précision'),
('VAC0815', 'Vaccin Pneumo - Hib ,\nsans précision', 'VAC0815 - Vaccin Pneumo - Hib ,\nsans précision'),
('VAC0997', 'Vaccin Pneumocoque\nconjugué 13 - valent , sans\nprécision', 'VAC0997 - Vaccin Pneumocoque\nconjugué 13 - valent , sans\nprécision'),
('VAC0324', 'Vaccin Pneumocoque\nconjugué 7 - valent , sans\nprécision', 'VAC0324 - Vaccin Pneumocoque\nconjugué 7 - valent , sans\nprécision'),
('VAC0814', 'Vaccin Pneumocoque\nconjugué , sans précision', 'VAC0814 - Vaccin Pneumocoque\nconjugué , sans précision'),
('VAC0339', 'Vaccin Pneumocoque\nnon conjugué 23 - valent ,\nsans précision', 'VAC0339 - Vaccin Pneumocoque\nnon conjugué 23 - valent ,\nsans précision'),
('VAC0813', 'Vaccin Pneumocoque\nnon conjugué , sans\nprécision', 'VAC0813 - Vaccin Pneumocoque\nnon conjugué , sans\nprécision'),
('VAC0157', 'Vaccin Pneumocoque ,\nsans précision', 'VAC0157 - Vaccin Pneumocoque ,\nsans précision'),
('VAC0270', 'Vaccin Polio inactivé ,\nsans précision', 'VAC0270 - Vaccin Polio inactivé ,\nsans précision'),
('VAC0802', 'Vaccin Polio oral\nmonovalent - type non\nconnu , sans précision', 'VAC0802 - Vaccin Polio oral\nmonovalent - type non\nconnu , sans précision'),
('VAC0320', 'Vaccin Polio oral\ntrivalent , sans précision', 'VAC0320 - Vaccin Polio oral\ntrivalent , sans précision'),
('VAC0135', 'Vaccin Polio , sans\nprécision', 'VAC0135 - Vaccin Polio , sans\nprécision'),
('VAC0084', 'Vaccin prépandémique\nH5N1 contre la grippe ,\nsans précision', 'VAC0084 - Vaccin prépandémique\nH5N1 contre la grippe ,\nsans précision'),
('VAC0943', 'Vaccin Rage cellules\ndiploïdes , sans précision', 'VAC0943 - Vaccin Rage cellules\ndiploïdes , sans précision'),
('VAC0942', 'Vaccin Rage embryon de\npoulet , sans précision', 'VAC0942 - Vaccin Rage embryon de\npoulet , sans précision'),
('VAC0905', 'Vaccin Rage PHKCV ,\nsans précision', 'VAC0905 - Vaccin Rage PHKCV ,\nsans précision'),
('VAC0904', 'Vaccin Rage préparé sur\nembryon de canard ,\nsans précision', 'VAC0904 - Vaccin Rage préparé sur\nembryon de canard ,\nsans précision'),
('VAC0903', 'Vaccin Rage type\nFuenzalida , sans\nprécision', 'VAC0903 - Vaccin Rage type\nFuenzalida , sans\nprécision'),
('VAC0902', 'Vaccin Rage type\nSemple , sans précision', 'VAC0902 - Vaccin Rage type\nSemple , sans précision'),
('VAC0131', 'Vaccin Rage , sans\nprécision', 'VAC0131 - Vaccin Rage , sans\nprécision'),
('VAC0623', 'Vaccin RO - Rougeole\nOreillons , sans précision', 'VAC0623 - Vaccin RO - Rougeole\nOreillons , sans précision'),
('VAC0130', 'Vaccin ROR ( ou RRO ) ,\nsans précision', 'VAC0130 - Vaccin ROR ( ou RRO ) ,\nsans précision'),
('VAC0827', 'Vaccin ROR - V\nRougeole - Oreillons\nRubéole - Varicelle , sans\nprécision', 'VAC0827 - Vaccin ROR - V\nRougeole - Oreillons\nRubéole - Varicelle , sans\nprécision'),
('VAC0828', 'Vaccin Rotavirus\npentavalent , sans\nprécision', 'VAC0828 - Vaccin Rotavirus\npentavalent , sans\nprécision'),
('VAC0158', 'Vaccin Rotavirus , sans\nprécision', 'VAC0158 - Vaccin Rotavirus , sans\nprécision'),
('VAC0114', 'Vaccin Rougeoleux ,\nmonovalent , sans\nprécision', 'VAC0114 - Vaccin Rougeoleux ,\nmonovalent , sans\nprécision'),
('VAC0550', 'Vaccin RR - Rougeole\nRubéole , sans précision', 'VAC0550 - Vaccin RR - Rougeole\nRubéole , sans précision'),
('VAC0113', 'Vaccin Rubéole , sans\nprécision', 'VAC0113 - Vaccin Rubéole , sans\nprécision'),
('VAC0829', 'Vaccin Rubéole\nOreillons , sans précision', 'VAC0829 - Vaccin Rubéole\nOreillons , sans précision'),
('VAC0794', 'Vaccin T - igT - Tétanos ,\nsans précision', 'VAC0794 - Vaccin T - igT - Tétanos ,\nsans précision'),
('VAC0380', 'Vaccin TP - Tétanos\npolio , sans précision', 'VAC0380 - Vaccin TP - Tétanos\npolio , sans précision'),
('VAC0849', 'Vaccin Tularémie , sans\nprécision', 'VAC0849 - Vaccin Tularémie , sans\nprécision'),
('VAC0712', 'Vaccin Typh - HepA -\nTyphoïde - Hépatite A ,\nsans précision', 'VAC0712 - Vaccin Typh - HepA -\nTyphoïde - Hépatite A ,\nsans précision'),
('VAC0818', 'Vaccin Typho\nParatyphoïdique , sans\nprécision', 'VAC0818 - Vaccin Typho\nParatyphoïdique , sans\nprécision'),
('VAC0711', 'Vaccin Typhoïde\nconjugué , sans précision', 'VAC0711 - Vaccin Typhoïde\nconjugué , sans précision'),
('VAC0817', 'Vaccin Typhoïde entier\ninactivé , sans précision', 'VAC0817 - Vaccin Typhoïde entier\ninactivé , sans précision'),
('VAC0424', 'Vaccin Typhoïde oral\nvivant atténué , sans\nprécision', 'VAC0424 - Vaccin Typhoïde oral\nvivant atténué , sans\nprécision'),
('VAC0713', 'Vaccin Typhoïde\npolyosidique , sans\nprécision', 'VAC0713 - Vaccin Typhoïde\npolyosidique , sans\nprécision'),
('VAC0112', 'Vaccin Typhoïde , sans\nprécision', 'VAC0112 - Vaccin Typhoïde , sans\nprécision'),
('VAC0512', 'Vaccin Typhus , sans\nprécision', 'VAC0512 - Vaccin Typhus , sans\nprécision'),
('VAC0132', 'Vaccin Tétanique , sans\nprécision', 'VAC0132 - Vaccin Tétanique , sans\nprécision'),
('VAC0159', 'Vaccin Varicelle , sans\nprécision', 'VAC0159 - Vaccin Varicelle , sans\nprécision'),
('VAC0133', 'Vaccin Variole , sans\nprécision', 'VAC0133 - Vaccin Variole , sans\nprécision'),
('VAC0899', 'Vaccin Virus\nParainfluenza humains ,\nsans précision', 'VAC0899 - Vaccin Virus\nParainfluenza humains ,\nsans précision'),
('VAC0923', 'Vaccin Virus\nRespiratoire Syncytial ,\nsans précision', 'VAC0923 - Vaccin Virus\nRespiratoire Syncytial ,\nsans précision'),
('VAC0922', 'Vaccin vivant atténué\ncontre les Adénovirus ,\ntype 4 et type 7 , voie\norale , sans précision', 'VAC0922 - Vaccin vivant atténué\ncontre les Adénovirus ,\ntype 4 et type 7 , voie\norale , sans précision'),
('VAC0830', 'Vaccin Zona sous\nunitaire , sans précision', 'VAC0830 - Vaccin Zona sous\nunitaire , sans précision'),
('VAC0160', 'Vaccin Zona vivant\natténué , sans précision', 'VAC0160 - Vaccin Zona vivant\natténué , sans précision'),
('VAC0906', 'Vaccin Zona , sans\nprécision', 'VAC0906 - Vaccin Zona , sans\nprécision');
