-- --------------------------------------------------------

--
-- Structure de la table `tests`
--

CREATE TABLE `tests` (
  `nom_complet` varchar(255) NOT NULL,
  `Codes_Biowin` varchar(255) NOT NULL,
  `Nom_analyse` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `tests`
--

INSERT INTO `tests` (`nom_complet`, `Codes_Biowin`, `Nom_analyse`, `created_at`, `updated_at`) VALUES
('ACE - ACE', 'ACE', 'ACE', NULL, NULL),
('Acetone urinaire - CET', 'CET', 'Acetone urinaire', NULL, NULL),
('\"Acide urique Acide urique femme en- ceinte - AU\"', 'AU', '\"Acide urique Acide urique femme en- ceinte\"', NULL, NULL),
('Acide urique urinaire - AUU', 'AUU', 'Acide urique urinaire', NULL, NULL),
('Acide valproique - DEPA', 'DEPA', 'Acide valproique', NULL, NULL),
('Actinomyces - ACTI', 'ACTI', 'Actinomyces', NULL, NULL),
('Adenovirus - ADENO', 'ADENO', 'Adenovirus', NULL, NULL),
('Agglutinines irregulieres - RAI', 'RAI', 'Agglutinines irregulieres', NULL, NULL),
('Albumine - ALB A+ A24+', 'ALB A+ A24+', 'Albumine', NULL, NULL),
('Alpha foetoproteine - AFP', 'AFP', 'Alpha foetoproteine', NULL, NULL),
('Amylase - AMY', 'AMY', 'Amylase', NULL, NULL),
('Anguillule - ANG', 'ANG', 'Anguillule', NULL, NULL),
('\"Anticorps anti Ag nu- cleaires solubles - ANS\"', 'ANS', '\"Anticorps anti Ag nu- cleaires solubles\"', NULL, NULL),
('\"Anticorps anti-Beta2GP1 IgG IgM - AB2 AB2G AB2M\"', '\"AB2 AB2G AB2M\"', '\"Anticorps anti-Beta2GP1 IgG IgM\"', NULL, NULL),
('\"Anticorps anti- Cardiolipine IgG IgM - ACL ACLG ACLM\"', 'ACL ACLG ACLM', '\"Anticorps anti- Cardiolipine IgG IgM\"', NULL, NULL),
('Anticoprs anti-DNA natifs - DNA', 'DNA', 'Anticoprs anti-DNA natifs', NULL, NULL),
('Anticorps anti-nucleaires - AANU', 'AANU', 'Anticorps anti-nucleaires', NULL, NULL),
('\"Anticorps anti-peptide citrullines - ACCP\"', 'ACCP', '\"Anticorps anti-peptide citrullines\"', NULL, NULL),
('\"Anticoprs anti-recepteur de la TSH - TRAK\"', 'TRAK', '\"Anticoprs anti-recepteur de la TSH\"', NULL, NULL),
('\"Anticorps anti-strepto- coque Anticorps anti-streptodor- nase Anticorps anti-streptoly- sine O - ASLO+ASD ASD ASLO\"', 'ASLO+ASD ASD ASLO', '\"Anticorps anti-strepto- coque Anticorps anti-streptodor- nase Anticorps anti-streptoly- sine O\"', NULL, NULL),
('\"Anticorps anti- thyroïdiens Anticorps anti-peroxydase Anticorps anti thyroglobuline - AAT ATPO ATG\"', 'AAT ATPO ATG', '\"Anticorps anti- thyroïdiens Anticorps anti-peroxydase Anticorps anti thyroglobuline\"', NULL, NULL),
('\"Anticorps anti- transglutaminase (tTG) - ATR ATRA\"', '\"ATR ATRA\"', '\"Anticorps anti- transglutaminase (tTG)\"', NULL, NULL),
('\"IgA anti-tTG IgG anti-tTG - ATRG\"', 'ATRG', '\"IgA anti-tTG IgG anti-tTG\"', NULL, NULL),
('APO A1 - BL1', 'BL1', 'APO A1', NULL, NULL),
('APO B - APOB', 'APOB', 'APO B', NULL, NULL),
('Aspergillus (culture) - GER', 'GER', 'Aspergillus (culture)', NULL, NULL),
('Bandelette urinaire - A + S + NIT + LEUEST + SGU', 'A + S + NIT + LEUEST + SGU', 'Bandelette urinaire', NULL, NULL),
('Beta 2 microglobuline - B2M', 'B2M', 'Beta 2 microglobuline', NULL, NULL),
('\"Bilan hepatique - PHB PHEP\"', '\"PHB PHEP\"', 'Bilan hepatique', NULL, NULL),
('Bilan lipidique - BL1', 'BL1', 'Bilan lipidique', NULL, NULL),
('Bilharziose urinaire - BILH', 'BILH', 'Bilharziose urinaire', NULL, NULL),
('Bilirubine totale - BT', 'BT', 'Bilirubine totale', NULL, NULL),
('Bilirubine urinaire - SPB', 'SPB', 'Bilirubine urinaire', NULL, NULL),
('BMR (dans les selles et anus) - BLSE', 'BLSE', 'BMR (dans les selles et anus)', NULL, NULL),
('\"BMR (enterocoque resi- tant vancomycine) - ERV\"', 'ERV', '\"BMR (enterocoque resi- tant vancomycine)\"', NULL, NULL),
('SARM', 'gorge et cutane)\"', '\"BMR (dans le nez', NULL, NULL),
('BNP - BNP', 'BNP', 'BNP', NULL, NULL),
('C3 - C3', 'C3', 'C3', NULL, NULL),
('C4 - C4', 'C4', 'C4', NULL, NULL),
('CA 125 - C125', 'C125', 'CA 125', NULL, NULL),
('CA 15.3 - C153', 'C153', 'CA 15.3', NULL, NULL),
('CA 19.9 - C199', 'C199', 'CA 19.9', NULL, NULL),
('\"Calcium corrige Calcium Calcium urinaire - CACO CA CAU\"', '\"CACO CA CAU\"', '\"Calcium corrige Calcium Calcium urinaire\"', NULL, NULL),
('Cannabis urinaire - CANNA', 'CANNA', 'Cannabis urinaire', NULL, NULL),
('CDT - CDTEC', 'CDTEC', 'CDT', NULL, NULL),
('Chlamydiae - CHLAM', 'CHLAM', 'Chlamydiae', NULL, NULL),
('Chlamydiae trachomatis IGG - SCHL', 'SCHL', 'Chlamydiae trachomatis IGG', NULL, NULL),
('Chlore - CL', 'CL', 'Chlore', NULL, NULL),
('Chlore urinaire - CLU', 'CLU', 'Chlore urinaire', NULL, NULL),
('Cholesterol total - CT', 'CT', 'Cholesterol total', NULL, NULL),
('Clostridium difficile - CLOS', 'CLOS', 'Clostridium difficile', NULL, NULL),
('CMV - CMV', 'CMV', 'CMV', NULL, NULL),
('Coproculture - COPR', 'COPR', 'Coproculture', NULL, NULL),
('\"Cortisol Cortisol apres-midi Cortisol apres dexametha- sone - COR COR2 COR5\"', 'COR COR2 COR5', '\"Cortisol Cortisol apres-midi Cortisol apres dexametha- sone\"', NULL, NULL),
('Cotinine - COTIN', 'COTIN', 'Cotinine', NULL, NULL),
('CPK - CPK', 'CPK', 'CPK', NULL, NULL),
('Creatine - MDRD CR COCK', 'MDRD CR COCK', 'Creatine', NULL, NULL),
('Creatine clairance - CLCR', 'CLCR', 'Creatine clairance', NULL, NULL),
('\"Creatine urinaire - CRUE CRU\"', '\"CRUE CRU\"', 'Creatine urinaire', NULL, NULL),
('Cristaux - CRIS', 'CRIS', 'Cristaux', NULL, NULL),
('CRP - CRP', 'CRP', 'CRP', NULL, NULL),
('Culot urinaire - CUL', 'CUL', 'Culot urinaire', NULL, NULL),
('D-Dimeres - DDIM', 'DDIM', 'D-Dimeres', NULL, NULL),
('Demodex - DEM', 'DEM', 'Demodex', NULL, NULL),
('Densite urinaire - DENS', 'DENS', 'Densite urinaire', NULL, NULL),
('Depakine - DEPA', 'DEPA', 'Depakine', NULL, NULL),
('Digoxine - DIGO', 'DIGO', 'Digoxine', NULL, NULL),
('DUKE - DUKE', 'DUKE', 'DUKE', NULL, NULL),
('ECBU - ECBU', 'ECBU', 'ECBU', NULL, NULL),
('\"Electrophorese de l\'hemoglobine - ELHB\"', 'ELHB', '\"Electrophorese de l\'hemoglobine\"', NULL, NULL),
('\"Electrophorese des proteines - ELPP\"', 'ELPP', '\"Electrophorese des proteines\"', NULL, NULL),
('Epstein Barr Virus - EBV', 'EBV', 'Epstein Barr Virus', NULL, NULL),
('Estradiol - E2', 'E2', 'Estradiol', NULL, NULL),
('Examen mycologique - MYCO', 'MYCO', 'Examen mycologique', NULL, NULL),
('\"Examen cytobacteriolo- gique d\'un pus - PUS\"', 'PUS', '\"Examen cytobacteriolo- gique d\'un pus\"', NULL, NULL),
('Expectoration - EXP', 'EXP', 'Expectoration', NULL, NULL),
('\"Exploration d\'une anoma- lie lipidique - BL1\"', 'BL1', '\"Exploration d\'une anoma- lie lipidique\"', NULL, NULL),
('\"Facteur rhumatoïde / Waaler Rose - FR\"', 'FR', '\"Facteur rhumatoïde / Waaler Rose\"', NULL, NULL),
('Fer serique - FE', 'FE', 'Fer serique', NULL, NULL),
('Ferritine - FERI', 'FERI', 'Ferritine', NULL, NULL),
('Fibrinogene - FIB', 'FIB', 'Fibrinogene', NULL, NULL),
('FSH - FSH', 'FSH', 'FSH', NULL, NULL),
('Gale - DEM', 'DEM', 'Gale', NULL, NULL),
('Gamma GT - GGT', 'GGT', 'Gamma GT', NULL, NULL),
('\"Glycemie - GL (tube gris = exterieur) ou G (tube sec =seulement si au labo)\"', '\"GL (tube gris = exterieur) ou G (tube sec =seulement si au labo)\"', 'Glycemie', NULL, NULL),
('Glycemie : Cycle glyce- mique - G1/G2/G3/G4/G5', 'G1/G2/G3/G4/G5', 'Glycemie : Cycle glyce- mique', NULL, NULL),
('\"Glycemie : Hyperglycemie provoquee - GL7524 pour femmes en- ceintes HGP pour hommes et femmes non enceintes\"', '\"GL7524 pour femmes en- ceintes HGP pour hommes et femmes non enceintes\"', 'Glycemie : Hyperglycemie provoquee', NULL, NULL),
('Glycemie post-prandiale - GPP', 'GPP', 'Glycemie post-prandiale', NULL, NULL),
('Glycosurie - S+ S24+', 'S+ S24+', 'Glycosurie', NULL, NULL),
('Gonocoque - GONO', 'GONO', 'Gonocoque', NULL, NULL),
('Groupe sanguin - GS GS2', 'GS GS2', 'Groupe sanguin', NULL, NULL),
('Haptoglobine - HAPTO', 'HAPTO', 'Haptoglobine', NULL, NULL),
('HCG - BHCG', 'BHCG', 'HCG', NULL, NULL),
('HDL - Cholesterol - BL1', 'BL1', 'HDL - Cholesterol', NULL, NULL),
('Hemoculture - HMB HM', 'HMB HM', 'Hemoculture', NULL, NULL),
('Hemoglobine glyquee - HBG', 'HBG', 'Hemoglobine glyquee', NULL, NULL),
('\"Hepatite A - HAV + MHAV + VA\"', '\"HAV + MHAV + VA\"', 'Hepatite A', NULL, NULL),
('Hepatite B Antigene HBS Anticorps anti HBS Anticorps anti HBC - SHB3 HBS + VB CHBS + VB CHBC + VB', 'SHB3 HBS + VB CHBS + VB CHBC + VB', 'Hepatite B Antigene HBS Anticorps anti HBS Anticorps anti HBC', NULL, NULL),
('Hepatite C - HCV', 'HCV', 'Hepatite C', NULL, NULL),
('HIV - HIV', 'HIV', 'HIV', NULL, NULL),
('HLM - HLM', 'HLM', 'HLM', NULL, NULL),
('\"Immunoglobulines IGA IGG IGM - IG IGA IGG IGM\"', 'IG IGA IGG IGM', '\"Immunoglobulines IGA IGG IGM\"', NULL, NULL),
('Immuno-electrophorese des proteines - IEP + ELPP', 'IEP + ELPP', 'Immuno-electrophorese des proteines', NULL, NULL),
('Ionogramme - IO', 'IO', 'Ionogramme', NULL, NULL),
('LDL - Cholesterol - BL1', 'BL1', 'LDL - Cholesterol', NULL, NULL),
('Lactate deshydrogenase - LDH', 'LDH', 'Lactate deshydrogenase', NULL, NULL),
('Legionnelle - LEGIO', 'LEGIO', 'Legionnelle', NULL, NULL),
('Leishmaniose cutanee - LEIS', 'LEIS', 'Leishmaniose cutanee', NULL, NULL),
(' - ', '', '', NULL, NULL),
('Leucocytes - LEUEST', 'LEUEST', 'Leucocytes', NULL, NULL),
('Levures - LEV', 'LEV', 'Levures', NULL, NULL),
('LH - LH', 'LH', 'LH', NULL, NULL),
('Lipase - LIPA', 'LIPA', 'Lipase', NULL, NULL),
('Liquide de ponction - LIQ', 'LIQ', 'Liquide de ponction', NULL, NULL),
('Lithium - LI', 'LI', 'Lithium', NULL, NULL),
('Lyme - LYME', 'LYME', 'Lyme', NULL, NULL),
('Magnesium Magnesium urinaire - MG MGU', 'MG MGU', 'Magnesium Magnesium urinaire', NULL, NULL),
('Malassezia spp - MAL', 'MAL', 'Malassezia spp', NULL, NULL),
('\"Micro-albuminurie - MIC24 MICE\"', '\"MIC24 MICE\"', 'Micro-albuminurie', NULL, NULL),
('Microfilaires - FIL', 'FIL', 'Microfilaires', NULL, NULL),
('MNI tests - MNI', 'MNI', 'MNI tests', NULL, NULL),
('\"Mycoplasmes Mycoplasmes urogenitaux serologie - MPF MPH MPS\"', 'MPF MPH MPS', '\"Mycoplasmes Mycoplasmes urogenitaux serologie\"', NULL, NULL),
('Nitrites - NIT', 'NIT', 'Nitrites', NULL, NULL),
('Numeration formule san- guine - NF', 'NF', 'Numeration formule san- guine', NULL, NULL),
('Orosomucoide - OROSO', 'OROSO', 'Orosomucoide', NULL, NULL),
('\"Osmolarite Osmolarite urinaire - OSMS OSM\"', '\"OSMS OSM\"', '\"Osmolarite Osmolarite urinaire\"', NULL, NULL),
('Oxyures (scotch tests) - SCO', 'SCO', 'Oxyures (scotch tests)', NULL, NULL),
('PALU', ' goutte epaisse\"', '\"Paludisme', NULL, NULL),
('Parasitologie des selles - PARA', 'PARA', 'Parasitologie des selles', NULL, NULL),
('Parathormone - PTH', 'PTH', 'Parathormone', NULL, NULL),
('PH urinaire - PH', 'PH', 'PH urinaire', NULL, NULL),
('Phosphatases alcalines - PAL', 'PAL', 'Phosphatases alcalines', NULL, NULL),
('Phosphore Phosphore urinaire - P PU', 'P PU', 'Phosphore Phosphore urinaire', NULL, NULL),
('Pigments biliaires - SPB', 'SPB', 'Pigments biliaires', NULL, NULL),
('PINI - PINI', 'PINI', 'PINI', NULL, NULL),
('Plaquettes - PL PLC', 'PL PLC', 'Plaquettes', NULL, NULL),
(' - ', '', '', NULL, NULL),
('\"Potassium Potassium urinaire - K KU\"', '\"K KU\"', '\"Potassium Potassium urinaire\"', NULL, NULL),
('Prealbumine - PREAL', 'PREAL', 'Prealbumine', NULL, NULL),
('Prelevement auriculaire - OREIL', 'OREIL', 'Prelevement auriculaire', NULL, NULL),
('\"Prelevement cutaneo- muqueux - PEAU\"', 'PEAU', '\"Prelevement cutaneo- muqueux\"', NULL, NULL),
('Prelevement de gorge - PG', 'PG', 'Prelevement de gorge', NULL, NULL),
('Prelevement de pus - PUS', 'PUS', 'Prelevement de pus', NULL, NULL),
('Prelevement mycologique - MYCO + RMYC', 'MYCO + RMYC', 'Prelevement mycologique', NULL, NULL),
('Prelevement nasal - NEZ', 'NEZ', 'Prelevement nasal', NULL, NULL),
('Prelevement oculaire - ŒIL', 'ŒIL', 'Prelevement oculaire', NULL, NULL),
('Prelevement uretral - PUR', 'PUR', 'Prelevement uretral', NULL, NULL),
('Prelevement vaginal - PV', 'PV', 'Prelevement vaginal', NULL, NULL),
('Progesterone - PROG', 'PROG', 'Progesterone', NULL, NULL),
('Prolactine - PROL', 'PROL', 'Prolactine', NULL, NULL),
('\"Proteines totales seriques Proteinurie - PROT A / A24\"', '\"PROT A / A24\"', '\"Proteines totales seriques Proteinurie\"', NULL, NULL),
('PSA total PSA libre et total - PSA PSALI', 'PSA PSALI', 'PSA total PSA libre et total', NULL, NULL),
('\"Recherche d\'agglutinines irregulieres - RAI\"', 'RAI', '\"Recherche d\'agglutinines irregulieres\"', NULL, NULL),
('\"RAI SI hemoglobine inferieure a ? - RAISI\"', 'RAISI', '\"RAI SI hemoglobine inferieure a ?\"', NULL, NULL),
('Reserve alcaline - RA', 'RA', 'Reserve alcaline', NULL, NULL),
('Reticulocytes - RETI', 'RETI', 'Reticulocytes', NULL, NULL),
('Rotavirus - ROTA', 'ROTA', 'Rotavirus', NULL, NULL),
('Rubeole serologie - RUB', 'RUB', 'Rubeole serologie', NULL, NULL),
('\"Sang dans les selles - RSS RSS2 RSS3\"', '\"RSS RSS2 RSS3\"', 'Sang dans les selles', NULL, NULL),
('Sang dans les urines - SGU', 'SGU', 'Sang dans les urines', NULL, NULL),
('\"Saturation de la transfe- rine - SATU\"', 'SATU', '\"Saturation de la transfe- rine\"', NULL, NULL),
('Sediments urinaires - CUL', 'CUL', 'Sediments urinaires', NULL, NULL),
('\"Sodium Sodium urinaire - NA NAU\"', '\"NA NAU\"', '\"Sodium Sodium urinaire\"', NULL, NULL),
('Spermoculture - SPC', 'SPC', 'Spermoculture', NULL, NULL),
('Staphylocoque aureus - SA / SARM', 'SA / SARM', 'Staphylocoque aureus', NULL, NULL),
(' - ', '', '', NULL, NULL),
('Sterilet - STER', 'STER', 'Sterilet', NULL, NULL),
('Streptocoque B - SGB', 'SGB', 'Streptocoque B', NULL, NULL),
('Synacthene - SYN SYNIM', 'SYN SYNIM', 'Synacthene', NULL, NULL),
('Syphilis - BW', 'BW', 'Syphilis', NULL, NULL),
('\"Transaminases SGOT SGPT - OP OT PT\"', '\"OP OT PT\"', '\"Transaminases SGOT SGPT\"', NULL, NULL),
('T3 libre - T3', 'T3', 'T3 libre', NULL, NULL),
('T4 libre - T4', 'T4', 'T4 libre', NULL, NULL),
('\"Taux de reabsorption du phosphore - TRP\"', 'TRP', '\"Taux de reabsorption du phosphore\"', NULL, NULL),
('Taux de prothrombine - TPN TPK / TP', 'TPN TPK / TP', 'Taux de prothrombine', NULL, NULL),
('\"Temps de cephaline acti- vee - TCA\"', 'TCA', '\"Temps de cephaline acti- vee\"', NULL, NULL),
('Temps de saignement - DUKE / IVY', 'DUKE / IVY', 'Temps de saignement', NULL, NULL),
('Test de Huhner - THU', 'THU', 'Test de Huhner', NULL, NULL),
('Testosterone - TEST', 'TEST', 'Testosterone', NULL, NULL),
('Toxoplasmose serologie - TOXO', 'TOXO', 'Toxoplasmose serologie', NULL, NULL),
('Triglycerides - TRI', 'TRI', 'Triglycerides', NULL, NULL),
('\"Trophatop Adulte Trophatop Enfant (<15 ans) - TROA TROE\"', 'TROA TROE', '\"Trophatop Adulte Trophatop Enfant (<15 ans)\"', NULL, NULL),
('Troponine HS - TROT', 'TROT', 'Troponine HS', NULL, NULL),
('TSH ultra sensible - TSH', 'TSH', 'TSH ultra sensible', NULL, NULL),
('Uree Uree urinaire - U UU', 'U UU', 'Uree Uree urinaire', NULL, NULL),
('Urobilinogene urinaire - SPB', 'SPB', 'Urobilinogene urinaire', NULL, NULL),
('Vitamine B12 - B12', 'B12', 'Vitamine B12', NULL, NULL),
('Vitamine B9 - B9', 'B9', 'Vitamine B9', NULL, NULL),
('Vitamine D - VD', 'VD', 'Vitamine D', NULL, NULL),
('Vitamines D HN - VDHN', 'VDHN', 'Vitamines D HN', NULL, NULL),
('Vitesse de sedimentation - VS', 'VS', 'Vitesse de sedimentation', NULL, NULL);