apiVersion: v1
kind: Service
metadata:
  labels:
    app: hopitaux-db
  name: hopitaux-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: hopitaux-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hopitaux-db
  name: hopitaux-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hopitaux-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hopitaux-db
    spec:
      containers:
        - image: medicalife/hopitaux-db:latest
          name: hopitaux-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/hopitaux
              name: hopitaux-data
      restartPolicy: Always
      volumes:
        - name: hopitaux-data
          persistentVolumeClaim:
            claimName: hopitaux-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hopitaux-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi