apiVersion: v1
kind: Service
metadata:
  labels:
    app: soins-db
  name: soins-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: soins-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: soins-db
  name: soins-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soins-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: soins-db
    spec:
      containers:
        - image: medicalife/soins-db:latest
          name: soins-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/soins
              name: soins-data
      restartPolicy: Always
      volumes:
        - name: soins-data
          persistentVolumeClaim:
            claimName: soins-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soins-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi