apiVersion: v1
kind: Service
metadata:
  labels:
    app: soins-service
  name: soins-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: soins-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: soins-service
  name: soins-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soins-service
  template:
    metadata:
      labels:
        app: soins-service
    spec:
      containers:
        - image: medicalife/soins-service:latest
          name: soins-service
          ports:
            - containerPort: 80
              protocol: TCP
      dnsConfig:
        nameservers:
          - 8.8.8.8
      restartPolicy: Always