Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../crypto-material/ordererOrganizations/medicalife.dz/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer0.medicalife.dz:7050

    - &Nord
        Name: Nord
        ID: NordMSP
        MSPDir: ../crypto-material/peerOrganizations/nord.medicalife.dz/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NordMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('NordMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('NordMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('NordMSP.member')"
        AnchorPeers:
            - Host: peer0.nord.medicalife.dz
              Port: 8051

    - &Est
        Name: Est
        ID: EstMSP
        MSPDir: ../crypto-material/peerOrganizations/est.medicalife.dz/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('EstMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('EstMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('EstMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('EstMSP.member')"
        AnchorPeers:
            - Host: peer0.est.medicalife.dz
              Port: 8052
    - &Ouest
        Name: Ouest
        ID: OuestMSP
        MSPDir: ../crypto-material/peerOrganizations/ouest.medicalife.dz/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OuestMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OuestMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OuestMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OuestMSP.member')"
        AnchorPeers:
            - Host: peer0.ouest.medicalife.dz
              Port: 8053
    - &Sud
        Name: Sud
        ID: SudMSP
        MSPDir: ../crypto-material/peerOrganizations/sud.medicalife.dz/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SudMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('SudMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('SudMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('SudMSP.member')"
        AnchorPeers:
            - Host: peer0.sud.medicalife.dz
              Port: 8054

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
        - Host: orderer0.medicalife.dz
          Port: 7050
          ClientTLSCert: ../crypto-material/ordererOrganizations/medicalife.dz/orderers/orderer0.medicalife.dz/tls/server.crt
          ServerTLSCert: ../crypto-material/ordererOrganizations/medicalife.dz/orderers/orderer0.medicalife.dz/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ApNetworkProfile:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            ApConsortium:
                Organizations:
                    - *Nord
                    - *Est
                    - *Ouest
                    - *Sud
    ApChannelProfile:
        Consortium: ApConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Nord
                - *Est
                - *Ouest
                - *Sud
            Capabilities:
                <<: *ApplicationCapabilities
