apiVersion: v1
kind: Service
metadata:
  labels:
    app: rendez-vous-db
  name: rendez-vous-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: rendez-vous-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rendez-vous-db
  name: rendez-vous-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rendez-vous-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rendez-vous-db
    spec:
      containers:
        - image: medicalife/rendez-vous-db
          name: rendez-vous-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/rendez-vous
              name: rendez-vous-data
      restartPolicy: Always
      volumes:
        - name: rendez-vous-data
          persistentVolumeClaim:
            claimName: rendez-vous-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rendez-vous-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi