apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - image: abdou1307/notification-service:latest
          name: notification-service
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsConfig:
        nameservers:
          - 8.8.8.8
      restartPolicy: Always