apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-db
  name: notification-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: notification-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-db
  name: notification-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - image: abdou1307/notification-db:latest
          name: notification-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/notification
              name: notification-data
      restartPolicy: Always
      volumes:
        - name: notification-data
          persistentVolumeClaim:
            claimName: notification-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi