apiVersion: v1
kind: Service
metadata:
  name: interior
  annotations:
    konghq.com/protocol: https
spec:
  clusterIP: None  
  type: ClusterIP
  ports:
  - port: 6000
    targetPort: 6000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: interior
subsets:
- addresses:
  - ip: 192.168.144.244  
  ports:
  - port: 6000