apiVersion: v1
kind: Service
metadata:
  labels:
    app: ehr-db
  name: ehr-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: ehr-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ehr-db
  name: ehr-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ehr-db
    spec:
      containers:
        - image: medicalife/ehr-db:latest
          name: ehr-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/ehr
              name: ehr-data
      restartPolicy: Always
      volumes:
        - name: ehr-data
          persistentVolumeClaim:
            claimName: ehr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ehr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi